/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views;

import com.QLKS.DAO.authorization.Authorization;
import com.QLKS.DAO.authorization.IAuthorization;
import com.QLKS.Service.impl.nhan_vienService;
import com.QLKS.model.nhan_vienModel;
import com.QLKS.utils.security;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class SigninForm extends javax.swing.JFrame {

    /**
     * Creates new form SigninForm
     */
     nhan_vienService nhanService;

    public SigninForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        nhanService = new nhan_vienService();
    }

    public nhan_vienModel getSignIn() {
        String message_empty = " Không được để trống!";
        String message_error = " Tài khoản hoặc mật khẩu không chính sác!";
        boolean check_err = true;

        String userName = userName_txt.getText();
        String passwordStr = new String(password_txt.getPassword());
        String ms = "";
        jPanel2.removeAll();
       
        
        if (userName.length() == 0) {
            jPanel2.add(makeLoginMs(message_empty));
            check_err = false;
        }
        
        if (passwordStr.length() == 0) {
            jPanel2.add(makeLoginMs(message_empty));
             check_err = false;
        }

        if (check_err == true) {
            nhan_vienModel model = nhan_vienModel.getInstance();
            IAuthorization authorization = new Authorization(userName, passwordStr);
            model = nhanService.findByUserNameAndPassword(authorization);
            if (model != null) {
                boolean check_pass = security.checkPassword(passwordStr, model.getPassword());
                if (check_pass == true) {
                    return model;
                }
                else {
                    JOptionPane.showMessageDialog(this, "Tài Khoản Hoặc Mật Khẩu không chính sác");
                }
            } else {
                jPanel2.removeAll();
                jPanel2.add(makeLoginMs(message_error));
                jPanel2.revalidate();
                jPanel2.repaint();
            }

        }
        return null;
    }

    private JLabel makeLoginMs(String ms) {
        JLabel lb = new JLabel();
        lb.setPreferredSize(new Dimension(300, 30));
        lb.setSize(lb.getPreferredSize());
        lb.setMaximumSize(lb.getPreferredSize());
        lb.setText(ms);
        lb.setForeground(Color.RED);
        return lb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userName_txt = new javax.swing.JTextField();
        password_txt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(21, 25, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userName_txt.setBackground(new java.awt.Color(31, 36, 42));
        userName_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userName_txt.setForeground(new java.awt.Color(169, 224, 49));
        userName_txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        userName_txt.setCaretColor(new java.awt.Color(169, 224, 49));
        userName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_txtActionPerformed(evt);
            }
        });
        jPanel1.add(userName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 280, 40));

        password_txt.setBackground(new java.awt.Color(31, 36, 42));
        password_txt.setForeground(new java.awt.Color(169, 224, 49));
        password_txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        password_txt.setCaretColor(new java.awt.Color(169, 224, 49));
        jPanel1.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 280, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icons8_User_Shield_100px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 170, 80));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 160, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icons8_Lock_35px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 40, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icons8_Male_User_35px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 40, 40));

        jPanel2.setBackground(new java.awt.Color(21, 25, 28));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 280, 30));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/loginDefault.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPreferredSize(new java.awt.Dimension(75, 40));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/loginHover.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/loginClickVer2.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName_txtActionPerformed

    }//GEN-LAST:event_userName_txtActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       loginController loController = new loginController();
       loController.login(this);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SigninForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SigninForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SigninForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SigninForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SigninForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JTextField userName_txt;
    // End of variables declaration//GEN-END:variables
}
