/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views.JintenalFrame.action;

import com.QLKS.Service.impl.nhan_vienService;
import com.QLKS.model.nhan_vienModel;
import com.QLKS.utils.FileTypeFiler;
import com.QLKS.utils.fileUsingStream;
import com.QLKS.utils.imageHelper;
import static com.QLKS.views.mainFrame.changeColor;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class ITN_add_nhan_vien extends javax.swing.JInternalFrame {

    /**
     * Creates new form ITN_add_nhan_Viet
     */
    nhan_vienService nhan_vienService = new nhan_vienService();
    nhan_vienModel nhan_vien = nhan_vienModel.getInstance();
    CallBackAdd cb;
    boolean check = true;

    public interface CallBackAdd {

        void doAdd();
    }

    public ITN_add_nhan_vien(CallBackAdd cb) {
        initComponents();
        this.cb = cb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_gender = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        content1 = new javax.swing.JPanel();
        line_space = new javax.swing.JPanel();
        add_name = new javax.swing.JPanel();
        pnl_name_content = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_inputName = new javax.swing.JTextField();
        line_space1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_message = new javax.swing.JPanel();
        mess_error = new javax.swing.JLabel();
        pnl_birthDay = new javax.swing.JPanel();
        pnl_name_content1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        line_space2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        txt_err_date = new javax.swing.JLabel();
        pnl_gender = new javax.swing.JPanel();
        pnl_name_content2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnl_button_radio = new javax.swing.JPanel();
        radio_nam = new javax.swing.JRadioButton();
        radio_khac = new javax.swing.JRadioButton();
        radio_nu = new javax.swing.JRadioButton();
        line_space3 = new javax.swing.JPanel();
        pnl_image = new javax.swing.JPanel();
        pnl_image_small = new javax.swing.JPanel();
        lbl_showImage = new javax.swing.JLabel();
        pnl_button_click = new javax.swing.JPanel();
        line_image = new javax.swing.JPanel();
        line_image_label = new javax.swing.JLabel();
        button_image_file = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        content2 = new javax.swing.JPanel();
        line_space4 = new javax.swing.JPanel();
        add_email = new javax.swing.JPanel();
        pnl_name_content3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_inputEmail = new javax.swing.JTextField();
        line_space5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        mess_err_email = new javax.swing.JLabel();
        add_userName = new javax.swing.JPanel();
        pnl_name_content4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_inputUsername1 = new javax.swing.JTextField();
        line_space6 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        mess_err_userName = new javax.swing.JLabel();
        add_passWord = new javax.swing.JPanel();
        pnl_name_content5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        line_space7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        mess_err_password = new javax.swing.JLabel();
        add_passWord1 = new javax.swing.JPanel();
        pnl_name_content6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        line_space8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        mess_err_password_check = new javax.swing.JLabel();
        add_CMND = new javax.swing.JPanel();
        pnl_name_content7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_inputCMND = new javax.swing.JTextField();
        line_space9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        messa_err_cmnd = new javax.swing.JLabel();
        add_nhom_quyen = new javax.swing.JPanel();
        pnl_name_content8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        line_space10 = new javax.swing.JPanel();
        button_add = new javax.swing.JPanel();
        pnl_add = new javax.swing.JPanel();
        line_icon_button = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        pnl_out = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pnl_reset = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/icons8_hotel_star_20px.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1173, 800));
        setMinimumSize(new java.awt.Dimension(1173, 800));
        setPreferredSize(new java.awt.Dimension(1173, 800));

        header.setBackground(new java.awt.Color(8, 13, 23));
        header.setPreferredSize(new java.awt.Dimension(1007, 50));
        header.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(10, 50));
        header.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(10, 50));
        header.add(jLabel2, java.awt.BorderLayout.LINE_START);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(154, 231, 246));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thêm Mới Nhân Viên");
        header.add(jLabel3, java.awt.BorderLayout.CENTER);

        content1.setBackground(new java.awt.Color(48, 48, 48));
        content1.setPreferredSize(new java.awt.Dimension(550, 500));

        line_space.setBackground(new java.awt.Color(48, 48, 48));
        line_space.setPreferredSize(new java.awt.Dimension(550, 40));
        content1.add(line_space);

        add_name.setBackground(new java.awt.Color(36, 36, 36));
        add_name.setPreferredSize(new java.awt.Dimension(400, 40));
        add_name.setLayout(new java.awt.BorderLayout());

        pnl_name_content.setBackground(new java.awt.Color(16, 16, 16));
        pnl_name_content.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_name_content.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_name_content.add(jLabel4, java.awt.BorderLayout.LINE_END);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(154, 231, 246));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Họ và Tên");
        pnl_name_content.add(jLabel5, java.awt.BorderLayout.CENTER);

        add_name.add(pnl_name_content, java.awt.BorderLayout.LINE_START);

        txt_inputName.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputName.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputName.setCaretColor(new java.awt.Color(154, 231, 246));
        add_name.add(txt_inputName, java.awt.BorderLayout.CENTER);

        content1.add(add_name);

        line_space1.setBackground(new java.awt.Color(48, 48, 48));
        line_space1.setPreferredSize(new java.awt.Dimension(550, 40));
        line_space1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(48, 48, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space1.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(48, 48, 48));
        jPanel2.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        txt_message.setBackground(new java.awt.Color(48, 48, 48));
        txt_message.setLayout(new java.awt.BorderLayout());

        mess_error.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        mess_error.setForeground(new java.awt.Color(255, 0, 0));
        mess_error.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        txt_message.add(mess_error, java.awt.BorderLayout.CENTER);

        line_space1.add(txt_message, java.awt.BorderLayout.CENTER);

        content1.add(line_space1);

        pnl_birthDay.setBackground(new java.awt.Color(36, 36, 36));
        pnl_birthDay.setPreferredSize(new java.awt.Dimension(400, 40));
        pnl_birthDay.setLayout(new java.awt.BorderLayout());

        pnl_name_content1.setBackground(new java.awt.Color(16, 16, 16));
        pnl_name_content1.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_name_content1.setLayout(new java.awt.BorderLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_name_content1.add(jLabel6, java.awt.BorderLayout.LINE_END);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(154, 231, 246));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ngày Sinh");
        pnl_name_content1.add(jLabel7, java.awt.BorderLayout.CENTER);

        pnl_birthDay.add(pnl_name_content1, java.awt.BorderLayout.LINE_START);

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pnl_birthDay.add(jDateChooser1, java.awt.BorderLayout.CENTER);

        content1.add(pnl_birthDay);

        line_space2.setBackground(new java.awt.Color(48, 48, 48));
        line_space2.setPreferredSize(new java.awt.Dimension(550, 40));
        line_space2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(48, 48, 48));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel15.setBackground(new java.awt.Color(48, 48, 48));
        jPanel15.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel5.add(jPanel15, java.awt.BorderLayout.LINE_END);

        jPanel16.setBackground(new java.awt.Color(48, 48, 48));
        jPanel16.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel5.add(jPanel16, java.awt.BorderLayout.LINE_START);

        txt_err_date.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txt_err_date.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(txt_err_date, java.awt.BorderLayout.CENTER);

        line_space2.add(jPanel5, java.awt.BorderLayout.CENTER);

        content1.add(line_space2);

        pnl_gender.setBackground(new java.awt.Color(36, 36, 36));
        pnl_gender.setPreferredSize(new java.awt.Dimension(400, 40));
        pnl_gender.setLayout(new java.awt.BorderLayout());

        pnl_name_content2.setBackground(new java.awt.Color(16, 16, 16));
        pnl_name_content2.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_name_content2.setLayout(new java.awt.BorderLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_name_content2.add(jLabel8, java.awt.BorderLayout.LINE_END);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(154, 231, 246));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Giới Tính");
        pnl_name_content2.add(jLabel9, java.awt.BorderLayout.CENTER);

        pnl_gender.add(pnl_name_content2, java.awt.BorderLayout.LINE_START);

        pnl_button_radio.setBackground(new java.awt.Color(36, 36, 36));
        pnl_button_radio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radio_nam.setBackground(new java.awt.Color(27, 27, 27));
        buttonGroup_gender.add(radio_nam);
        radio_nam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radio_nam.setForeground(new java.awt.Color(154, 231, 246));
        radio_nam.setSelected(true);
        radio_nam.setText("Nam");
        radio_nam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radio_nam.setPreferredSize(new java.awt.Dimension(90, 40));
        pnl_button_radio.add(radio_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        radio_khac.setBackground(new java.awt.Color(27, 27, 27));
        buttonGroup_gender.add(radio_khac);
        radio_khac.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radio_khac.setForeground(new java.awt.Color(154, 231, 246));
        radio_khac.setText("Khác");
        radio_khac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radio_khac.setPreferredSize(new java.awt.Dimension(90, 40));
        radio_khac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_khacActionPerformed(evt);
            }
        });
        pnl_button_radio.add(radio_khac, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        radio_nu.setBackground(new java.awt.Color(27, 27, 27));
        buttonGroup_gender.add(radio_nu);
        radio_nu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        radio_nu.setForeground(new java.awt.Color(154, 231, 246));
        radio_nu.setText("Nữ");
        radio_nu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radio_nu.setPreferredSize(new java.awt.Dimension(90, 40));
        radio_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_nuActionPerformed(evt);
            }
        });
        pnl_button_radio.add(radio_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        pnl_gender.add(pnl_button_radio, java.awt.BorderLayout.CENTER);

        content1.add(pnl_gender);

        line_space3.setBackground(new java.awt.Color(48, 48, 48));
        line_space3.setPreferredSize(new java.awt.Dimension(550, 40));
        content1.add(line_space3);

        pnl_image.setPreferredSize(new java.awt.Dimension(200, 250));
        pnl_image.setLayout(new java.awt.BorderLayout());

        pnl_image_small.setBackground(new java.awt.Color(36, 36, 36));
        pnl_image_small.setPreferredSize(new java.awt.Dimension(200, 200));
        pnl_image_small.setLayout(new java.awt.BorderLayout());

        lbl_showImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/avatar_default.jpg"))); // NOI18N
        pnl_image_small.add(lbl_showImage, java.awt.BorderLayout.CENTER);

        pnl_image.add(pnl_image_small, java.awt.BorderLayout.PAGE_START);

        pnl_button_click.setLayout(new java.awt.BorderLayout());

        line_image.setBackground(new java.awt.Color(0, 0, 0));
        line_image.setPreferredSize(new java.awt.Dimension(200, 5));
        line_image.setLayout(new java.awt.BorderLayout());

        line_image_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        line_image.add(line_image_label, java.awt.BorderLayout.CENTER);

        pnl_button_click.add(line_image, java.awt.BorderLayout.PAGE_START);

        button_image_file.setBackground(new java.awt.Color(27, 27, 27));
        button_image_file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_image_fileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_image_fileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_image_fileMouseExited(evt);
            }
        });
        button_image_file.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(154, 231, 246));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Chọn Ảnh");
        button_image_file.add(jLabel10, java.awt.BorderLayout.CENTER);

        pnl_button_click.add(button_image_file, java.awt.BorderLayout.CENTER);

        pnl_image.add(pnl_button_click, java.awt.BorderLayout.CENTER);

        content1.add(pnl_image);

        content2.setBackground(new java.awt.Color(48, 48, 48));
        content2.setPreferredSize(new java.awt.Dimension(550, 500));

        line_space4.setBackground(new java.awt.Color(48, 48, 48));
        line_space4.setPreferredSize(new java.awt.Dimension(550, 40));
        content2.add(line_space4);

        add_email.setBackground(new java.awt.Color(36, 36, 36));
        add_email.setPreferredSize(new java.awt.Dimension(400, 40));
        add_email.setLayout(new java.awt.BorderLayout());

        pnl_name_content3.setBackground(new java.awt.Color(16, 16, 16));
        pnl_name_content3.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_name_content3.setLayout(new java.awt.BorderLayout());

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_name_content3.add(jLabel12, java.awt.BorderLayout.LINE_END);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(154, 231, 246));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Email");
        pnl_name_content3.add(jLabel13, java.awt.BorderLayout.CENTER);

        add_email.add(pnl_name_content3, java.awt.BorderLayout.LINE_START);

        txt_inputEmail.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputEmail.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputEmail.setCaretColor(new java.awt.Color(154, 231, 246));
        txt_inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inputEmailActionPerformed(evt);
            }
        });
        add_email.add(txt_inputEmail, java.awt.BorderLayout.CENTER);

        content2.add(add_email);

        line_space5.setBackground(new java.awt.Color(48, 48, 48));
        line_space5.setPreferredSize(new java.awt.Dimension(550, 40));
        line_space5.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(48, 48, 48));
        jPanel4.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space5.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(48, 48, 48));
        jPanel3.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space5.add(jPanel3, java.awt.BorderLayout.LINE_START);

        mess_err_email.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        mess_err_email.setForeground(new java.awt.Color(255, 0, 0));
        mess_err_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        line_space5.add(mess_err_email, java.awt.BorderLayout.CENTER);

        content2.add(line_space5);

        add_userName.setBackground(new java.awt.Color(36, 36, 36));
        add_userName.setPreferredSize(new java.awt.Dimension(400, 40));
        add_userName.setLayout(new java.awt.BorderLayout());

        pnl_name_content4.setBackground(new java.awt.Color(16, 16, 16));
        pnl_name_content4.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_name_content4.setLayout(new java.awt.BorderLayout());

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_name_content4.add(jLabel14, java.awt.BorderLayout.LINE_END);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(154, 231, 246));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tài Khoản");
        pnl_name_content4.add(jLabel15, java.awt.BorderLayout.CENTER);

        add_userName.add(pnl_name_content4, java.awt.BorderLayout.LINE_START);

        txt_inputUsername1.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputUsername1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputUsername1.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputUsername1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputUsername1.setCaretColor(new java.awt.Color(154, 231, 246));
        add_userName.add(txt_inputUsername1, java.awt.BorderLayout.CENTER);

        content2.add(add_userName);

        line_space6.setBackground(new java.awt.Color(48, 48, 48));
        line_space6.setPreferredSize(new java.awt.Dimension(550, 40));
        line_space6.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(48, 48, 48));
        jPanel6.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space6.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(48, 48, 48));
        jPanel7.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space6.add(jPanel7, java.awt.BorderLayout.LINE_END);

        mess_err_userName.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        mess_err_userName.setForeground(new java.awt.Color(255, 0, 0));
        mess_err_userName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        line_space6.add(mess_err_userName, java.awt.BorderLayout.CENTER);

        content2.add(line_space6);

        add_passWord.setBackground(new java.awt.Color(36, 36, 36));
        add_passWord.setPreferredSize(new java.awt.Dimension(400, 40));
        add_passWord.setLayout(new java.awt.BorderLayout());

        pnl_name_content5.setBackground(new java.awt.Color(16, 16, 16));
        pnl_name_content5.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_name_content5.setLayout(new java.awt.BorderLayout());

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_name_content5.add(jLabel16, java.awt.BorderLayout.LINE_END);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(154, 231, 246));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Mật Khẩu");
        pnl_name_content5.add(jLabel17, java.awt.BorderLayout.CENTER);

        add_passWord.add(pnl_name_content5, java.awt.BorderLayout.LINE_START);

        jPasswordField1.setBackground(new java.awt.Color(32, 32, 32));
        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(154, 231, 246));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        jPasswordField1.setCaretColor(new java.awt.Color(154, 231, 246));
        add_passWord.add(jPasswordField1, java.awt.BorderLayout.CENTER);

        content2.add(add_passWord);

        line_space7.setBackground(new java.awt.Color(48, 48, 48));
        line_space7.setPreferredSize(new java.awt.Dimension(550, 40));
        line_space7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(48, 48, 48));
        jPanel8.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space7.add(jPanel8, java.awt.BorderLayout.LINE_START);

        jPanel9.setBackground(new java.awt.Color(48, 48, 48));
        jPanel9.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space7.add(jPanel9, java.awt.BorderLayout.LINE_END);

        mess_err_password.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        mess_err_password.setForeground(new java.awt.Color(255, 0, 0));
        mess_err_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        line_space7.add(mess_err_password, java.awt.BorderLayout.CENTER);

        content2.add(line_space7);

        add_passWord1.setBackground(new java.awt.Color(36, 36, 36));
        add_passWord1.setPreferredSize(new java.awt.Dimension(400, 40));
        add_passWord1.setLayout(new java.awt.BorderLayout());

        pnl_name_content6.setBackground(new java.awt.Color(16, 16, 16));
        pnl_name_content6.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_name_content6.setLayout(new java.awt.BorderLayout());

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_name_content6.add(jLabel18, java.awt.BorderLayout.LINE_END);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(154, 231, 246));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Nhập Lại MK");
        pnl_name_content6.add(jLabel19, java.awt.BorderLayout.CENTER);

        add_passWord1.add(pnl_name_content6, java.awt.BorderLayout.LINE_START);

        jPasswordField2.setBackground(new java.awt.Color(32, 32, 32));
        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(154, 231, 246));
        jPasswordField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        jPasswordField2.setCaretColor(new java.awt.Color(154, 231, 246));
        add_passWord1.add(jPasswordField2, java.awt.BorderLayout.CENTER);

        content2.add(add_passWord1);

        line_space8.setBackground(new java.awt.Color(48, 48, 48));
        line_space8.setPreferredSize(new java.awt.Dimension(550, 40));
        line_space8.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(48, 48, 48));
        jPanel10.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space8.add(jPanel10, java.awt.BorderLayout.LINE_START);

        jPanel11.setBackground(new java.awt.Color(48, 48, 48));
        jPanel11.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space8.add(jPanel11, java.awt.BorderLayout.LINE_END);

        mess_err_password_check.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        mess_err_password_check.setForeground(new java.awt.Color(255, 0, 0));
        mess_err_password_check.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        line_space8.add(mess_err_password_check, java.awt.BorderLayout.CENTER);

        content2.add(line_space8);

        add_CMND.setBackground(new java.awt.Color(36, 36, 36));
        add_CMND.setPreferredSize(new java.awt.Dimension(400, 40));
        add_CMND.setLayout(new java.awt.BorderLayout());

        pnl_name_content7.setBackground(new java.awt.Color(16, 16, 16));
        pnl_name_content7.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_name_content7.setLayout(new java.awt.BorderLayout());

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_name_content7.add(jLabel20, java.awt.BorderLayout.LINE_END);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(154, 231, 246));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("CMND");
        pnl_name_content7.add(jLabel21, java.awt.BorderLayout.CENTER);

        add_CMND.add(pnl_name_content7, java.awt.BorderLayout.LINE_START);

        txt_inputCMND.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputCMND.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputCMND.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputCMND.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputCMND.setCaretColor(new java.awt.Color(154, 231, 246));
        add_CMND.add(txt_inputCMND, java.awt.BorderLayout.CENTER);

        content2.add(add_CMND);

        line_space9.setBackground(new java.awt.Color(48, 48, 48));
        line_space9.setPreferredSize(new java.awt.Dimension(550, 40));
        line_space9.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(48, 48, 48));
        jPanel12.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space9.add(jPanel12, java.awt.BorderLayout.LINE_END);

        jPanel13.setBackground(new java.awt.Color(48, 48, 48));
        jPanel13.setPreferredSize(new java.awt.Dimension(80, 40));
        line_space9.add(jPanel13, java.awt.BorderLayout.LINE_START);

        jPanel14.setBackground(new java.awt.Color(48, 48, 48));
        jPanel14.setLayout(new java.awt.BorderLayout());

        messa_err_cmnd.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        messa_err_cmnd.setForeground(new java.awt.Color(255, 0, 0));
        messa_err_cmnd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jPanel14.add(messa_err_cmnd, java.awt.BorderLayout.CENTER);

        line_space9.add(jPanel14, java.awt.BorderLayout.CENTER);

        content2.add(line_space9);

        add_nhom_quyen.setBackground(new java.awt.Color(36, 36, 36));
        add_nhom_quyen.setPreferredSize(new java.awt.Dimension(400, 40));
        add_nhom_quyen.setLayout(new java.awt.BorderLayout());

        pnl_name_content8.setBackground(new java.awt.Color(16, 16, 16));
        pnl_name_content8.setPreferredSize(new java.awt.Dimension(130, 40));
        pnl_name_content8.setLayout(new java.awt.BorderLayout());

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_name_content8.add(jLabel22, java.awt.BorderLayout.LINE_END);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(154, 231, 246));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Nhóm Quyền");
        pnl_name_content8.add(jLabel23, java.awt.BorderLayout.CENTER);

        add_nhom_quyen.add(pnl_name_content8, java.awt.BorderLayout.LINE_START);

        jComboBox1.setBackground(new java.awt.Color(36, 36, 36));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add_nhom_quyen.add(jComboBox1, java.awt.BorderLayout.CENTER);

        content2.add(add_nhom_quyen);

        line_space10.setBackground(new java.awt.Color(48, 48, 48));
        line_space10.setPreferredSize(new java.awt.Dimension(550, 40));
        content2.add(line_space10);

        button_add.setBackground(new java.awt.Color(36, 36, 36));
        button_add.setPreferredSize(new java.awt.Dimension(300, 40));
        button_add.setLayout(new java.awt.BorderLayout());

        pnl_add.setBackground(new java.awt.Color(11, 11, 11));
        pnl_add.setForeground(new java.awt.Color(154, 231, 246));
        pnl_add.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_addMouseExited(evt);
            }
        });
        pnl_add.setLayout(new java.awt.BorderLayout());

        line_icon_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        line_icon_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/line_button_add_NV.png"))); // NOI18N
        pnl_add.add(line_icon_button, java.awt.BorderLayout.LINE_END);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(154, 231, 246));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Thêm");
        pnl_add.add(jLabel26, java.awt.BorderLayout.CENTER);

        button_add.add(pnl_add, java.awt.BorderLayout.LINE_END);

        pnl_out.setBackground(new java.awt.Color(11, 11, 11));
        pnl_out.setForeground(new java.awt.Color(154, 231, 246));
        pnl_out.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_outMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_outMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_outMouseExited(evt);
            }
        });
        pnl_out.setLayout(new java.awt.BorderLayout());

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/line_button_add_NV.png"))); // NOI18N
        pnl_out.add(jLabel28, java.awt.BorderLayout.LINE_END);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/line_button_add_NV.png"))); // NOI18N
        pnl_out.add(jLabel30, java.awt.BorderLayout.LINE_START);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(154, 231, 246));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Thoát");
        pnl_out.add(jLabel29, java.awt.BorderLayout.CENTER);

        button_add.add(pnl_out, java.awt.BorderLayout.LINE_START);

        pnl_reset.setBackground(new java.awt.Color(11, 11, 11));
        pnl_reset.setForeground(new java.awt.Color(154, 231, 246));
        pnl_reset.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_resetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_resetMouseExited(evt);
            }
        });
        pnl_reset.setLayout(new java.awt.BorderLayout());

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/line_button_add_NV.png"))); // NOI18N
        pnl_reset.add(jLabel25, java.awt.BorderLayout.LINE_END);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(154, 231, 246));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Làm Mới");
        pnl_reset.add(jLabel27, java.awt.BorderLayout.CENTER);

        button_add.add(pnl_reset, java.awt.BorderLayout.CENTER);

        content2.add(button_add);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(content2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changeimage(JLabel btn, String resourceImage) {
        ImageIcon a = new ImageIcon(getClass().getResource(resourceImage));
        btn.setIcon(a);
    }

    public void hideShowMenu(JPanel menuClick, boolean check1, JLabel button) {
        if (check1 == true) {
            menuClick.setPreferredSize(new Dimension(150, this.getHeight()));
            changeimage(button, "/com/QLKS/icon/icon_button/icon_menuJpanelClick.png");
        } else {
            menuClick.setPreferredSize(new Dimension(0, this.getHeight()));
            changeimage(button, "/com/QLKS/icon/icon_button/custom-iconMenu.png");
        }
    }

    public void resetText() {
        txt_inputName.setText("");
        txt_inputEmail.setText("");
        txt_inputUsername1.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        txt_inputCMND.setText("");
    }
    private void radio_khacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_khacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_khacActionPerformed

    private void radio_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_nuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_nuActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void pnl_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addMouseEntered
        changeColor(pnl_add, new Color(78, 78, 78));
    }//GEN-LAST:event_pnl_addMouseEntered

    private void pnl_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addMouseExited
        changeColor(pnl_add, new Color(11, 11, 11));
        changeimage(line_icon_button, "/com/QLKS/icon/icon_button/line_button_add_NV.png");
    }//GEN-LAST:event_pnl_addMouseExited


    private void pnl_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addMouseClicked
        List<nhan_vienModel> Listnhan_vien = nhan_vienService.findAll();
        changeimage(line_icon_button, "/com/QLKS/icon/icon_button/button_add_NVCLICK.png");
        String name = txt_inputName.getText();
        String email = txt_inputEmail.getText();
        String userName = txt_inputUsername1.getText();
        String passwordStr = new String(jPasswordField1.getPassword());
        String passwordStr_check = new String(jPasswordField2.getPassword());
        String cmnd = txt_inputCMND.getText();
        String gioiTinh = "nam";
        java.util.Date utilStartDate = jDateChooser1.getDate();

        if (!Listnhan_vien.isEmpty()) {
            try {
                if (name.length() == 0) {
                    mess_error.setText("Tên không được để trống!");
                    check = false;
                } else if (name.length() > 100) {
                    mess_error.setText("Tên phải lớn hơn 100 ký tự!");
                    check = false;
                } else {
                    mess_error.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            try {
                if (utilStartDate == null) {
                    txt_err_date.setText("Không được để trống!");
                    check = false;

                } else {
                    txt_err_date.setText("");

                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            try {
                nhan_vien = nhan_vienService.findByEmail(email);
                if (nhan_vien.getEmail().equals(email) == true) {
                    mess_err_email.setText("Email đã tồn tại!");
                    check = false;
                }
                else if (email.length() == 0) {
                    mess_err_email.setText("Email Không được để trống!");
                    check = false;
                } else if (email.length() > 150) {
                    mess_err_email.setText("Email phải lớn hơn 150 ký tự!");
                    check = false;
                } else {
                    mess_err_email.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            try {
//                nhan_vien = Listnhan_vien.stream().filter(nhan_vien -> userName.equals(nhan_vien.getUserName())).findAny().orElse(nhan_vien);
                nhan_vien = nhan_vienService.findByUserName(userName);
                if (nhan_vien.getUserName().equals(userName) == true) {
                    mess_err_userName.setText("Tên đăng nhập đã tồn tại!");
                    check = false;
                } else if (userName.length() == 0) {
                    mess_err_userName.setText("Tên đăng nhập không được để trống!");
                    check = false;
                } else if (userName.length() > 50) {
                    mess_err_userName.setText("Tên đăng nhập phải nhỏ hơn 50 ký tự!");
                    check = false;
                } //                else if (nhan_vien != null) {
                //                    mess_err_userName.setText("Tên đăng nhập đã tồn tại!");
                //                    check = false;
                //                } 
                else {
                    mess_err_email.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            try {
                if (passwordStr.length() == 0) {
                    mess_err_password.setText("Mật khẩu không được để trống!");
                    check = false;
                } else if (passwordStr.length() < 8 || passwordStr.length() > 50) {
                    mess_err_password.setText("Mật khẩu phải từ 8 -> 50 ký tự!");
                    check = false;
                } else {
                    mess_err_password.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            try {
                if (passwordStr_check.length() == 0) {
                    mess_err_password_check.setText("Không được để trống!");
                    check = false;
                } else if (passwordStr_check.length() < 3 || passwordStr_check.length() > 50) {
                    mess_err_password_check.setText("Mật khẩu phải từ 3 -> 50 ký tự!");
                    check = false;
                }
                if (passwordStr_check.equals(passwordStr) == false) {
                    mess_err_password_check.setText("Mật khẩu nhập lại không đúng!");
                    check = false;
                } else {
                    mess_err_password_check.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            try {
//                nhan_vien = Listnhan_vien.stream().filter(nhan_vien -> cmnd.equals(nhan_vien.getCmnd())).findAny().orElse(nhan_vien);
                nhan_vien = nhan_vienService.findByCmnd(cmnd);
                if (nhan_vien.getCmnd().equals(cmnd) == true) {
                    messa_err_cmnd.setText("CMND đã tồn tại trong hệ thống!");
                    check = false;
                } else if (cmnd.length() == 0) {
                    messa_err_cmnd.setText("CMND không Được để Trống!");
                    check = false;
                } else if (cmnd.length() > 12 || cmnd.length() < 12) {
                    messa_err_cmnd.setText("CMND phải bằng 12 ký tự");
                    check = false;
                } //                else if (nhan_vien != null) {
                //                    messa_err_cmnd.setText("CMND đã tồn tại");
                //                    check = false;
                //                } 
                else {
                    messa_err_cmnd.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

//            nhan_vien = Listnhan_vien.stream().filter(nhan_vienModel -> email.equals(nhan_vienModel.getEmail())).findAny().orElse(nhan_vien);
            if (email.length() == 0) {
                mess_err_email.setText("Email không được để trống!");
                check = false;

            } else if (email.length() > 150) {
                mess_err_email.setText("Email phải nhở hơn 150 ký tự!");
                check = false;
            } //            } else if (nhan_vien != null) {
            //                mess_err_email.setText("Email đã tồn tại!");
            //                check = false;
            //            }
            else {
                mess_err_email.setText("");
            }

            if (check = true) {
                nhan_vien.setName(name);
                if (utilStartDate != null) {
                    java.sql.Date sqlStartDate = new java.sql.Date(utilStartDate.getTime());
                    nhan_vien.setBirthDay(sqlStartDate);
                } else {
                    nhan_vien.setBirthDay(null);
                }
                try {
                    if (radio_nam.isSelected()) {
                        nhan_vien.setGender(gioiTinh);
                    } else if (radio_nu.isSelected()) {
                        gioiTinh = "nữ";
                        nhan_vien.setGender(gioiTinh);
                    } else if (radio_khac.isSelected()) {
                        gioiTinh = "Khác";
                        nhan_vien.setGender(gioiTinh);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                nhan_vien.setEmail(email);
                nhan_vien.setCmnd(cmnd);
                nhan_vien.setUserName(userName);
                nhan_vien.setPassword(passwordStr);
                System.out.println(nhan_vien.getName().toString());

                nhan_vien = nhan_vienService.add(nhan_vien);
                if (nhan_vien != null) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm Mới Thành Công!");
                    cb.doAdd();
                    resetText();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thêm Mới Thất Bại!");
                }
            }
        }


    }//GEN-LAST:event_pnl_addMouseClicked

    private void button_image_fileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_image_fileMouseEntered
        changeColor(pnl_add, new Color(0, 0, 0));
    }//GEN-LAST:event_button_image_fileMouseEntered

    private void button_image_fileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_image_fileMouseExited
        changeColor(pnl_add, new Color(27, 27, 27));
        changeimage(line_image_label, "/com/QLKS/icon/icon_button/line_button_add_NV.png");
    }//GEN-LAST:event_button_image_fileMouseExited

    private void button_image_fileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_image_fileMouseClicked
        changeimage(line_image_label, "/com/QLKS/icon/icon_button/line_button_add_NV.png");
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("Thêm ảnh");
        jFileChooser.setMultiSelectionEnabled(false);
        jFileChooser.setFileFilter(new FileTypeFiler(".jpg", "JPG"));
        jFileChooser.setFileFilter(new FileTypeFiler(".gif", "GIF"));
        jFileChooser.setFileFilter(new FileTypeFiler(".png", "png"));
        int resutl = jFileChooser.showOpenDialog(null);
        if (resutl == jFileChooser.APPROVE_OPTION) {
            File fileSource = jFileChooser.getSelectedFile();
            File fileDest = new File(("src/com/QLKS/icon/image/avatar/" + fileSource.getName()));
            try {
                fileUsingStream.copyFileUsingStream(fileSource, fileDest);
                ImageIcon icon = new ImageIcon(fileDest.getPath());
                Image img = imageHelper.resize(icon.getImage(), 180, 180);
                ImageIcon resizedIcon = new ImageIcon(img);
                lbl_showImage.setIcon(resizedIcon);
                nhan_vien.setImage(imageHelper.toByteArray(img, "jpg"));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_button_image_fileMouseClicked

    private void pnl_resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_resetMouseEntered
        changeColor(pnl_reset, new Color(0, 0, 0));
    }//GEN-LAST:event_pnl_resetMouseEntered

    private void pnl_resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_resetMouseExited
        changeColor(pnl_reset, new Color(27, 27, 27));
        changeimage(jLabel25, "/com/QLKS/icon/icon_button/line_button_add_NV.png");
    }//GEN-LAST:event_pnl_resetMouseExited

    private void pnl_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_resetMouseClicked
        resetText();
        changeimage(lbl_showImage, "/com/QLKS/icon/icon_button/avatar_default.png");
        changeimage(jLabel25, "/com/QLKS/icon/icon_button/button_add_NVCLICK.png");
        jDateChooser1.setCalendar(null);
    }//GEN-LAST:event_pnl_resetMouseClicked

    private void pnl_outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_outMouseEntered
        changeColor(pnl_out, new Color(0, 0, 0));
    }//GEN-LAST:event_pnl_outMouseEntered

    private void pnl_outMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_outMouseExited
        changeColor(pnl_out, new Color(27, 27, 27));
        changeimage(jLabel28, "/com/QLKS/icon/icon_button/line_button_add_NV.png");
        changeimage(jLabel30, "/com/QLKS/icon/icon_button/line_button_add_NV.png");
    }//GEN-LAST:event_pnl_outMouseExited

    private void pnl_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_outMouseClicked
        changeimage(jLabel28, "/com/QLKS/icon/icon_button/button_add_NVCLICK.png");
        changeimage(jLabel30, "/com/QLKS/icon/icon_button/button_add_NVCLICK.png");
        resetText();
        dispose();
    }//GEN-LAST:event_pnl_outMouseClicked


    private void txt_inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inputEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_CMND;
    private javax.swing.JPanel add_email;
    private javax.swing.JPanel add_name;
    private javax.swing.JPanel add_nhom_quyen;
    private javax.swing.JPanel add_passWord;
    private javax.swing.JPanel add_passWord1;
    private javax.swing.JPanel add_userName;
    private javax.swing.ButtonGroup buttonGroup_gender;
    private javax.swing.JPanel button_add;
    private javax.swing.JPanel button_image_file;
    private javax.swing.JPanel content1;
    private javax.swing.JPanel content2;
    private javax.swing.JPanel header;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel lbl_showImage;
    private javax.swing.JLabel line_icon_button;
    private javax.swing.JPanel line_image;
    private javax.swing.JLabel line_image_label;
    private javax.swing.JPanel line_space;
    private javax.swing.JPanel line_space1;
    private javax.swing.JPanel line_space10;
    private javax.swing.JPanel line_space2;
    private javax.swing.JPanel line_space3;
    private javax.swing.JPanel line_space4;
    private javax.swing.JPanel line_space5;
    private javax.swing.JPanel line_space6;
    private javax.swing.JPanel line_space7;
    private javax.swing.JPanel line_space8;
    private javax.swing.JPanel line_space9;
    private javax.swing.JLabel mess_err_email;
    private javax.swing.JLabel mess_err_password;
    private javax.swing.JLabel mess_err_password_check;
    private javax.swing.JLabel mess_err_userName;
    private javax.swing.JLabel mess_error;
    private javax.swing.JLabel messa_err_cmnd;
    private javax.swing.JPanel pnl_add;
    private javax.swing.JPanel pnl_birthDay;
    private javax.swing.JPanel pnl_button_click;
    private javax.swing.JPanel pnl_button_radio;
    private javax.swing.JPanel pnl_gender;
    private javax.swing.JPanel pnl_image;
    private javax.swing.JPanel pnl_image_small;
    private javax.swing.JPanel pnl_name_content;
    private javax.swing.JPanel pnl_name_content1;
    private javax.swing.JPanel pnl_name_content2;
    private javax.swing.JPanel pnl_name_content3;
    private javax.swing.JPanel pnl_name_content4;
    private javax.swing.JPanel pnl_name_content5;
    private javax.swing.JPanel pnl_name_content6;
    private javax.swing.JPanel pnl_name_content7;
    private javax.swing.JPanel pnl_name_content8;
    private javax.swing.JPanel pnl_out;
    private javax.swing.JPanel pnl_reset;
    private javax.swing.JRadioButton radio_khac;
    private javax.swing.JRadioButton radio_nam;
    private javax.swing.JRadioButton radio_nu;
    private javax.swing.JLabel txt_err_date;
    private javax.swing.JTextField txt_inputCMND;
    private javax.swing.JTextField txt_inputEmail;
    private javax.swing.JTextField txt_inputName;
    private javax.swing.JTextField txt_inputUsername1;
    private javax.swing.JPanel txt_message;
    // End of variables declaration//GEN-END:variables
}
