/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views.JintenalFrame.action;

import com.QLKS.Service.impl.khuyen_maiService;
import com.QLKS.model.khuyen_maiModel;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author steve
 */
public class ITN_add_khuyenmai extends javax.swing.JInternalFrame implements ITN_UPDATE_EDNDATE.CallbackDate {

    /**
     * Creates new form ITN_add_khuyenmai
     */
    khuyen_maiModel khuyen_maiModel;
    khuyen_maiService khuyen_maiService;
    CallBackAdd cb;
    SimpleDateFormat sf;
    private JDesktopPane jdek;

    @Override
    public void doSendDate(Date endDate) {
        if (endDate != null) {
            java.sql.Date sqlDateEndT = new java.sql.Date(endDate.getTime());
            String newDateStr = sf.format(endDate);
            String oldDateStr = sf.format(khuyen_maiModel.getThoi_gian_ket_thuc());
            boolean check_dateT = checkEndDate(oldDateStr, newDateStr);
            if (check_dateT == true) {
                khuyen_maiModel.setThoi_gian_ket_thuc(sqlDateEndT);
                int key = khuyen_maiService.edit(khuyen_maiModel);
                if (key > 0) {
                    JOptionPane.showMessageDialog(this, "Đổi Trạng Thái Thành Công!");
                    ressetText();
                    cb.doAdd();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Đổi Trạng Thái thất bại!");
                }
            }
        } else {
            khuyen_maiModel.setThoi_gian_ket_thuc(null);
        }
    }

    public interface CallBackAdd {

        void doAdd();
    }

    public ITN_add_khuyenmai(CallBackAdd _cb) {
        initComponents();
        this.cb = _cb;
        khuyen_maiModel = new khuyen_maiModel();
        khuyen_maiService = new khuyen_maiService();
        sf = new SimpleDateFormat("dd/MM/yyyy");
    }

    public void ressetText() {
        txt_IDKM.setText("");
        txt_inputCode.setText("");
        txt_inputValue.setText("0");
        txt_inputContent.setText("");
    }

    public boolean checkEndDate(String OldEndDate, String newEndDate) {
        if (OldEndDate.equals(newEndDate) == true) {
            return false;
        }
        return true;
    }

    public void centerJIF(JInternalFrame jif) {
        Dimension desktopSize = jdek.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }

    public void showInternalFrame(JInternalFrame jif) {
        if (!jif.isVisible()) {
            jdek = getDesktopPane();
            jdek.add(jif);
            centerJIF(jif);
            jif.setVisible(true);
            jdek.show();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        idKM = new javax.swing.JPanel();
        pnl_idKM = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_IDKM = new javax.swing.JLabel();
        codeKM = new javax.swing.JPanel();
        pnl_codeKM = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_inputCode = new javax.swing.JTextField();
        valueKM = new javax.swing.JPanel();
        pnl_valueKM = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_inputValue = new javax.swing.JTextField();
        contentKM = new javax.swing.JPanel();
        pnl_contentKM = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_inputContent = new javax.swing.JTextField();
        typeKM = new javax.swing.JPanel();
        pnl_typeKM = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnl_typeKM1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        date_end = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnl_add = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnl_reset = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnl_edit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        radio_type_on = new javax.swing.JRadioButton();
        radio_type_off = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        date_start = new com.toedter.calendar.JDateChooser();

        setClosable(true);

        header.setBackground(new java.awt.Color(8, 13, 23));
        header.setPreferredSize(new java.awt.Dimension(626, 40));
        header.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 231, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm mới khuyến mãi");
        header.add(jLabel1, java.awt.BorderLayout.CENTER);

        content.setBackground(new java.awt.Color(48, 48, 48));

        idKM.setBackground(new java.awt.Color(36, 36, 36));
        idKM.setPreferredSize(new java.awt.Dimension(320, 45));
        idKM.setLayout(new java.awt.BorderLayout());

        pnl_idKM.setBackground(new java.awt.Color(16, 16, 16));
        pnl_idKM.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_idKM.setLayout(new java.awt.BorderLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_idKM.add(jLabel6, java.awt.BorderLayout.LINE_END);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(154, 231, 246));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mã khuyến mãi");
        pnl_idKM.add(jLabel7, java.awt.BorderLayout.CENTER);

        idKM.add(pnl_idKM, java.awt.BorderLayout.LINE_START);

        txt_IDKM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_IDKM.setForeground(new java.awt.Color(154, 231, 246));
        txt_IDKM.setText("...");
        txt_IDKM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        idKM.add(txt_IDKM, java.awt.BorderLayout.CENTER);

        codeKM.setBackground(new java.awt.Color(36, 36, 36));
        codeKM.setPreferredSize(new java.awt.Dimension(320, 45));
        codeKM.setLayout(new java.awt.BorderLayout());

        pnl_codeKM.setBackground(new java.awt.Color(16, 16, 16));
        pnl_codeKM.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_codeKM.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_codeKM.add(jLabel4, java.awt.BorderLayout.LINE_END);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(154, 231, 246));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Code");
        pnl_codeKM.add(jLabel5, java.awt.BorderLayout.CENTER);

        codeKM.add(pnl_codeKM, java.awt.BorderLayout.LINE_START);

        txt_inputCode.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputCode.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputCode.setCaretColor(new java.awt.Color(154, 231, 246));
        codeKM.add(txt_inputCode, java.awt.BorderLayout.CENTER);

        valueKM.setBackground(new java.awt.Color(36, 36, 36));
        valueKM.setPreferredSize(new java.awt.Dimension(320, 45));
        valueKM.setLayout(new java.awt.BorderLayout());

        pnl_valueKM.setBackground(new java.awt.Color(16, 16, 16));
        pnl_valueKM.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_valueKM.setLayout(new java.awt.BorderLayout());

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_valueKM.add(jLabel10, java.awt.BorderLayout.LINE_END);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(154, 231, 246));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Value");
        pnl_valueKM.add(jLabel11, java.awt.BorderLayout.CENTER);

        valueKM.add(pnl_valueKM, java.awt.BorderLayout.LINE_START);

        txt_inputValue.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputValue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputValue.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputValue.setText("0");
        txt_inputValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputValue.setCaretColor(new java.awt.Color(154, 231, 246));
        valueKM.add(txt_inputValue, java.awt.BorderLayout.CENTER);

        contentKM.setBackground(new java.awt.Color(36, 36, 36));
        contentKM.setPreferredSize(new java.awt.Dimension(320, 45));
        contentKM.setLayout(new java.awt.BorderLayout());

        pnl_contentKM.setBackground(new java.awt.Color(16, 16, 16));
        pnl_contentKM.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_contentKM.setLayout(new java.awt.BorderLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_contentKM.add(jLabel8, java.awt.BorderLayout.LINE_END);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(154, 231, 246));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nội Dung");
        pnl_contentKM.add(jLabel9, java.awt.BorderLayout.CENTER);

        contentKM.add(pnl_contentKM, java.awt.BorderLayout.LINE_START);

        txt_inputContent.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputContent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputContent.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputContent.setCaretColor(new java.awt.Color(154, 231, 246));
        contentKM.add(txt_inputContent, java.awt.BorderLayout.CENTER);

        typeKM.setBackground(new java.awt.Color(36, 36, 36));
        typeKM.setPreferredSize(new java.awt.Dimension(320, 45));
        typeKM.setLayout(new java.awt.BorderLayout());

        pnl_typeKM.setBackground(new java.awt.Color(16, 16, 16));
        pnl_typeKM.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_typeKM.setLayout(new java.awt.BorderLayout());

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_typeKM.add(jLabel12, java.awt.BorderLayout.LINE_END);

        pnl_typeKM1.setBackground(new java.awt.Color(16, 16, 16));
        pnl_typeKM1.setPreferredSize(new java.awt.Dimension(100, 30));
        pnl_typeKM1.setLayout(new java.awt.BorderLayout());

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_typeKM1.add(jLabel16, java.awt.BorderLayout.LINE_END);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(154, 231, 246));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Type");
        pnl_typeKM1.add(jLabel17, java.awt.BorderLayout.CENTER);

        pnl_typeKM.add(pnl_typeKM1, java.awt.BorderLayout.CENTER);

        typeKM.add(pnl_typeKM, java.awt.BorderLayout.CENTER);

        date_end.setDateFormatString("dd/MM/yyyy");
        date_end.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        date_end.setPreferredSize(new java.awt.Dimension(150, 40));

        jPanel1.setBackground(new java.awt.Color(11, 11, 11));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(154, 231, 246));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ngày Bắt Đầu");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnl_add.setBackground(new java.awt.Color(36, 36, 36));
        pnl_add.setMaximumSize(new java.awt.Dimension(100, 35));
        pnl_add.setMinimumSize(new java.awt.Dimension(100, 35));
        pnl_add.setPreferredSize(new java.awt.Dimension(90, 30));
        pnl_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_addMouseClicked(evt);
            }
        });
        pnl_add.setLayout(new java.awt.BorderLayout());

        jLabel14.setForeground(new java.awt.Color(154, 231, 246));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Thêm");
        pnl_add.add(jLabel14, java.awt.BorderLayout.CENTER);

        pnl_reset.setBackground(new java.awt.Color(36, 36, 36));
        pnl_reset.setMaximumSize(new java.awt.Dimension(100, 35));
        pnl_reset.setMinimumSize(new java.awt.Dimension(100, 35));
        pnl_reset.setPreferredSize(new java.awt.Dimension(90, 30));
        pnl_reset.setLayout(new java.awt.BorderLayout());

        jLabel15.setForeground(new java.awt.Color(154, 231, 246));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Làm mới");
        pnl_reset.add(jLabel15, java.awt.BorderLayout.CENTER);

        pnl_edit.setBackground(new java.awt.Color(36, 36, 36));
        pnl_edit.setMaximumSize(new java.awt.Dimension(100, 35));
        pnl_edit.setMinimumSize(new java.awt.Dimension(100, 35));
        pnl_edit.setPreferredSize(new java.awt.Dimension(90, 30));
        pnl_edit.setLayout(new java.awt.BorderLayout());

        jLabel3.setForeground(new java.awt.Color(154, 231, 246));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thoát");
        pnl_edit.add(jLabel3, java.awt.BorderLayout.CENTER);

        radio_type_on.setBackground(new java.awt.Color(27, 27, 27));
        buttonGroup1.add(radio_type_on);
        radio_type_on.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        radio_type_on.setForeground(new java.awt.Color(154, 231, 246));
        radio_type_on.setSelected(true);
        radio_type_on.setText("Hoạt Động");

        radio_type_off.setBackground(new java.awt.Color(27, 27, 27));
        buttonGroup1.add(radio_type_off);
        radio_type_off.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        radio_type_off.setForeground(new java.awt.Color(154, 231, 246));
        radio_type_off.setText("Đã Ngưng");

        jPanel2.setBackground(new java.awt.Color(11, 11, 11));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 40));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(154, 231, 246));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ngày Kết Thúc");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        date_start.setDateFormatString("dd/MM/yyyy");
        date_start.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        date_start.setPreferredSize(new java.awt.Dimension(150, 40));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(pnl_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(pnl_reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contentKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeKM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(radio_type_on)
                                .addGap(82, 82, 82)
                                .addComponent(radio_type_off)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(date_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date_end, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(116, 116, 116))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(idKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(codeKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(valueKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(contentKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(typeKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_type_on)
                            .addComponent(radio_type_off))))
                .addGap(37, 37, 37)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_start, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date_end, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_add, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(content, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_addMouseClicked
        String inputCode = txt_inputCode.getText();
        Float inputValue = Float.parseFloat(txt_inputValue.getText());
        String inputContent = txt_inputContent.getText();
        java.util.Date utilDateStart = date_start.getDate();
        java.util.Date ultilDateEnd = date_end.getDate();

        boolean check_km = true;
        if (inputContent.length() < 1 || inputContent.length() > 250) {
            JOptionPane.showMessageDialog(this, "Nội dung khuyến mãi phải nhập!");
            check_km = false;
        }

        if (utilDateStart == ultilDateEnd) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu không được bằng ngày kết thúc");
            check_km = false;
        }

        boolean check_type = true;
        if (radio_type_off.isSelected()) {
            check_type = false;
        }
        if (check_km == true) {
            khuyen_maiModel getCodeKM = khuyen_maiService.findByCode(inputCode);
            if (getCodeKM == null) {
                khuyen_maiModel.setCode(inputCode);
                khuyen_maiModel.setValue(inputValue);
                khuyen_maiModel.setContent(inputContent);
                khuyen_maiModel.setType(check_type);
                if (utilDateStart != null) {
                    java.sql.Date sqlDateStart = new java.sql.Date(utilDateStart.getTime());
                    khuyen_maiModel.setThoi_gian_bat_dau(sqlDateStart);
                } else {
                    khuyen_maiModel.setThoi_gian_bat_dau(null);
                }

                if (ultilDateEnd != null) {
                    java.sql.Date sqlDateEnd = new java.sql.Date(ultilDateEnd.getTime());
                    khuyen_maiModel.setThoi_gian_ket_thuc(sqlDateEnd);
                } else {
                    khuyen_maiModel.setThoi_gian_ket_thuc(null);
                }

                Long key = khuyen_maiService.add(khuyen_maiModel);
                if (key > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thành Công!");
                    ressetText();
                    cb.doAdd();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thất Bại!");
                }
            } else {
                if (getCodeKM.isType() == true) {
                    JOptionPane.showMessageDialog(this, "Mã Khuyến Mại Đã Tồn Tại Và Đang Sử Dụng!");
                    ressetText();
                } else {
                    int thongBao = JOptionPane.showConfirmDialog(this, "Mã Khuyến Mại này đang tồn tại, Bạn muốn sử dụng?", "Thông báo!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (thongBao == JOptionPane.YES_OPTION) {
                        khuyen_maiModel.setId(getCodeKM.getId());
                        khuyen_maiModel.setCode(getCodeKM.getCode());
                        khuyen_maiModel.setValue(getCodeKM.getValue());
                        khuyen_maiModel.setContent(getCodeKM.getContent());
                        khuyen_maiModel.setType(true);
                        khuyen_maiModel.setThoi_gian_bat_dau(getCodeKM.getThoi_gian_bat_dau());
                        khuyen_maiModel.setThoi_gian_ket_thuc(getCodeKM.getThoi_gian_ket_thuc());
                        ITN_UPDATE_EDNDATE ITN_END = new ITN_UPDATE_EDNDATE(this);
                        showInternalFrame(ITN_END);
                    } else if (thongBao == JOptionPane.NO_OPTION) {
                        dispose();
                    }
                }
            }

        }
    }//GEN-LAST:event_pnl_addMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel codeKM;
    private javax.swing.JPanel content;
    private javax.swing.JPanel contentKM;
    private com.toedter.calendar.JDateChooser date_end;
    private com.toedter.calendar.JDateChooser date_start;
    private javax.swing.JPanel header;
    private javax.swing.JPanel idKM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnl_add;
    private javax.swing.JPanel pnl_codeKM;
    private javax.swing.JPanel pnl_contentKM;
    private javax.swing.JPanel pnl_edit;
    private javax.swing.JPanel pnl_idKM;
    private javax.swing.JPanel pnl_reset;
    private javax.swing.JPanel pnl_typeKM;
    private javax.swing.JPanel pnl_typeKM1;
    private javax.swing.JPanel pnl_valueKM;
    private javax.swing.JRadioButton radio_type_off;
    private javax.swing.JRadioButton radio_type_on;
    private javax.swing.JLabel txt_IDKM;
    private javax.swing.JTextField txt_inputCode;
    private javax.swing.JTextField txt_inputContent;
    private javax.swing.JTextField txt_inputValue;
    private javax.swing.JPanel typeKM;
    private javax.swing.JPanel valueKM;
    // End of variables declaration//GEN-END:variables
}
