/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views.JintenalFrame.action;

import com.QLKS.Service.impl.khuyen_maiService;
import com.QLKS.model.khuyen_maiModel;
import javax.swing.JOptionPane;

/**
 *
 * @author steve
 */
public class ITN_edit_khuyenmai extends javax.swing.JInternalFrame {

    /**
     * Creates new form ITN_add_khuyenmai
     */
    CallbackUpdate ud;
    khuyen_maiService khuyen_maiService;
    khuyen_maiModel khuyen_maiModel;

    public interface CallbackUpdate {

        void doUpdate();
    }

    public ITN_edit_khuyenmai(khuyen_maiModel oldModel, CallbackUpdate _ud) {
        initComponents();
        this.ud = _ud;
        khuyen_maiService = new khuyen_maiService();
        khuyen_maiModel = new khuyen_maiModel();
        txt_inputID.setText(oldModel.getId().toString());
        txt_inputName.setText(oldModel.getCode());
        txt_inputValue.setText(String.valueOf(oldModel.getValue()));
        txt_inputContent.setText(oldModel.getContent());
        radio_suDung.setSelected(true);
        if (oldModel.isType() == false) {
            radio_hetHan.setSelected(true);
        }
        date_Start.setDate(oldModel.getThoi_gian_bat_dau());
        date_end.setDate(oldModel.getThoi_gian_ket_thuc());
    }

    public void ressetText() {
        txt_inputName.setText("");
        txt_inputValue.setText("");
        txt_inputContent.setText("");
        date_Start.setCalendar(null);
        date_end.setCalendar(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        idKM = new javax.swing.JPanel();
        pnl_idKM = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_inputID = new javax.swing.JTextField();
        codeKM = new javax.swing.JPanel();
        pnl_codeKM = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_inputName = new javax.swing.JTextField();
        valueKM = new javax.swing.JPanel();
        pnl_valueKM = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_inputValue = new javax.swing.JTextField();
        contentKM = new javax.swing.JPanel();
        pnl_contentKM = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_inputContent = new javax.swing.JTextField();
        typeKM = new javax.swing.JPanel();
        pnl_typeKM = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        radio_suDung = new javax.swing.JRadioButton();
        radio_hetHan = new javax.swing.JRadioButton();
        pnl_update = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnl_reset = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pnl_edit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        date_Start = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        date_end = new com.toedter.calendar.JDateChooser();

        header.setBackground(new java.awt.Color(8, 13, 23));
        header.setPreferredSize(new java.awt.Dimension(626, 40));
        header.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 231, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sửa khuyến mãi");
        header.add(jLabel1, java.awt.BorderLayout.CENTER);

        content.setBackground(new java.awt.Color(48, 48, 48));

        idKM.setBackground(new java.awt.Color(36, 36, 36));
        idKM.setPreferredSize(new java.awt.Dimension(320, 45));
        idKM.setLayout(new java.awt.BorderLayout());

        pnl_idKM.setBackground(new java.awt.Color(16, 16, 16));
        pnl_idKM.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_idKM.setLayout(new java.awt.BorderLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_idKM.add(jLabel6, java.awt.BorderLayout.LINE_END);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(154, 231, 246));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mã khuyến mãi");
        pnl_idKM.add(jLabel7, java.awt.BorderLayout.CENTER);

        idKM.add(pnl_idKM, java.awt.BorderLayout.LINE_START);

        txt_inputID.setEditable(false);
        txt_inputID.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputID.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputID.setCaretColor(new java.awt.Color(154, 231, 246));
        idKM.add(txt_inputID, java.awt.BorderLayout.CENTER);

        codeKM.setBackground(new java.awt.Color(36, 36, 36));
        codeKM.setPreferredSize(new java.awt.Dimension(320, 45));
        codeKM.setLayout(new java.awt.BorderLayout());

        pnl_codeKM.setBackground(new java.awt.Color(16, 16, 16));
        pnl_codeKM.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_codeKM.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_codeKM.add(jLabel4, java.awt.BorderLayout.LINE_END);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(154, 231, 246));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Code");
        pnl_codeKM.add(jLabel5, java.awt.BorderLayout.CENTER);

        codeKM.add(pnl_codeKM, java.awt.BorderLayout.LINE_START);

        txt_inputName.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputName.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputName.setCaretColor(new java.awt.Color(154, 231, 246));
        codeKM.add(txt_inputName, java.awt.BorderLayout.CENTER);

        valueKM.setBackground(new java.awt.Color(36, 36, 36));
        valueKM.setPreferredSize(new java.awt.Dimension(320, 45));
        valueKM.setLayout(new java.awt.BorderLayout());

        pnl_valueKM.setBackground(new java.awt.Color(16, 16, 16));
        pnl_valueKM.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_valueKM.setLayout(new java.awt.BorderLayout());

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_valueKM.add(jLabel10, java.awt.BorderLayout.LINE_END);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(154, 231, 246));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Value");
        pnl_valueKM.add(jLabel11, java.awt.BorderLayout.CENTER);

        valueKM.add(pnl_valueKM, java.awt.BorderLayout.LINE_START);

        txt_inputValue.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputValue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputValue.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputValue.setCaretColor(new java.awt.Color(154, 231, 246));
        txt_inputValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inputValueActionPerformed(evt);
            }
        });
        valueKM.add(txt_inputValue, java.awt.BorderLayout.CENTER);

        contentKM.setBackground(new java.awt.Color(36, 36, 36));
        contentKM.setPreferredSize(new java.awt.Dimension(320, 45));
        contentKM.setLayout(new java.awt.BorderLayout());

        pnl_contentKM.setBackground(new java.awt.Color(16, 16, 16));
        pnl_contentKM.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_contentKM.setLayout(new java.awt.BorderLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_contentKM.add(jLabel8, java.awt.BorderLayout.LINE_END);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(154, 231, 246));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Content");
        pnl_contentKM.add(jLabel9, java.awt.BorderLayout.CENTER);

        contentKM.add(pnl_contentKM, java.awt.BorderLayout.LINE_START);

        txt_inputContent.setBackground(new java.awt.Color(32, 32, 32));
        txt_inputContent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_inputContent.setForeground(new java.awt.Color(154, 231, 246));
        txt_inputContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txt_inputContent.setCaretColor(new java.awt.Color(154, 231, 246));
        txt_inputContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inputContentActionPerformed(evt);
            }
        });
        contentKM.add(txt_inputContent, java.awt.BorderLayout.CENTER);

        typeKM.setBackground(new java.awt.Color(36, 36, 36));
        typeKM.setPreferredSize(new java.awt.Dimension(320, 45));

        pnl_typeKM.setBackground(new java.awt.Color(16, 16, 16));
        pnl_typeKM.setPreferredSize(new java.awt.Dimension(100, 40));
        pnl_typeKM.setLayout(new java.awt.BorderLayout());

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setPreferredSize(new java.awt.Dimension(5, 40));
        pnl_typeKM.add(jLabel12, java.awt.BorderLayout.LINE_END);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(154, 231, 246));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Type");
        pnl_typeKM.add(jLabel13, java.awt.BorderLayout.CENTER);

        radio_suDung.setBackground(new java.awt.Color(27, 27, 27));
        buttonGroup1.add(radio_suDung);
        radio_suDung.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        radio_suDung.setForeground(new java.awt.Color(154, 231, 246));
        radio_suDung.setText("Đang Sử Dụng");

        radio_hetHan.setBackground(new java.awt.Color(27, 27, 27));
        buttonGroup1.add(radio_hetHan);
        radio_hetHan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        radio_hetHan.setForeground(new java.awt.Color(154, 231, 246));
        radio_hetHan.setText("Đã Hết Hạn");

        javax.swing.GroupLayout typeKMLayout = new javax.swing.GroupLayout(typeKM);
        typeKM.setLayout(typeKMLayout);
        typeKMLayout.setHorizontalGroup(
            typeKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeKMLayout.createSequentialGroup()
                .addComponent(pnl_typeKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radio_suDung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radio_hetHan))
        );
        typeKMLayout.setVerticalGroup(
            typeKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_typeKM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(typeKMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(typeKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_suDung)
                    .addComponent(radio_hetHan)))
        );

        pnl_update.setBackground(new java.awt.Color(36, 36, 36));
        pnl_update.setMaximumSize(new java.awt.Dimension(100, 35));
        pnl_update.setMinimumSize(new java.awt.Dimension(100, 35));
        pnl_update.setPreferredSize(new java.awt.Dimension(90, 30));
        pnl_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_updateMouseClicked(evt);
            }
        });
        pnl_update.setLayout(new java.awt.BorderLayout());

        jLabel14.setForeground(new java.awt.Color(154, 231, 246));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sửa");
        pnl_update.add(jLabel14, java.awt.BorderLayout.CENTER);

        pnl_reset.setBackground(new java.awt.Color(36, 36, 36));
        pnl_reset.setMaximumSize(new java.awt.Dimension(100, 35));
        pnl_reset.setMinimumSize(new java.awt.Dimension(100, 35));
        pnl_reset.setPreferredSize(new java.awt.Dimension(90, 30));
        pnl_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_resetMouseClicked(evt);
            }
        });
        pnl_reset.setLayout(new java.awt.BorderLayout());

        jLabel15.setForeground(new java.awt.Color(154, 231, 246));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Làm mới");
        pnl_reset.add(jLabel15, java.awt.BorderLayout.CENTER);

        pnl_edit.setBackground(new java.awt.Color(36, 36, 36));
        pnl_edit.setMaximumSize(new java.awt.Dimension(100, 35));
        pnl_edit.setMinimumSize(new java.awt.Dimension(100, 35));
        pnl_edit.setPreferredSize(new java.awt.Dimension(90, 30));
        pnl_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_editMouseClicked(evt);
            }
        });
        pnl_edit.setLayout(new java.awt.BorderLayout());

        jLabel3.setForeground(new java.awt.Color(154, 231, 246));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thoát");
        pnl_edit.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(27, 27, 27));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 45));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(13, 13, 13));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(154, 231, 246));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ngày Bắt Đầu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        date_Start.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(date_Start, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(27, 27, 27));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 45));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(13, 13, 13));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(154, 231, 246));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Ngày Kết Thúc");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.LINE_START);

        date_end.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(date_end, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(contentLayout.createSequentialGroup()
                            .addComponent(pnl_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(pnl_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(contentKM, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addComponent(idKM, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addComponent(codeKM, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addComponent(typeKM, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addComponent(valueKM, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(116, 116, 116))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(idKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(codeKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(valueKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(contentKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(typeKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_update, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_inputContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inputContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inputContentActionPerformed

    private void txt_inputValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inputValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inputValueActionPerformed

    private void pnl_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_updateMouseClicked
        Long InputMakm = Long.parseLong(txt_inputID.getText());
        String inputCode = txt_inputName.getText();
        Float inputValue = Float.parseFloat(txt_inputValue.getText());
        String inputContent = txt_inputContent.getText();
        java.util.Date utilDateStart = date_Start.getDate();
        java.util.Date ultilDateEnd = date_end.getDate();
        boolean check_TG = true;
        if (radio_hetHan.isSelected()) {
            check_TG = false;
        }

        khuyen_maiModel.setId(InputMakm);
        khuyen_maiModel.setCode(inputCode);
        khuyen_maiModel.setValue(inputValue);
        khuyen_maiModel.setContent(inputContent);
        khuyen_maiModel.setType(check_TG);
        if (utilDateStart != null) {
            java.sql.Date sqlDateStart = new java.sql.Date(utilDateStart.getTime());
            khuyen_maiModel.setThoi_gian_bat_dau(sqlDateStart);
        } else {
            khuyen_maiModel.setThoi_gian_bat_dau(null);
        }

        if (ultilDateEnd != null) {
            java.sql.Date sqlDateEnd = new java.sql.Date(ultilDateEnd.getTime());
            khuyen_maiModel.setThoi_gian_ket_thuc(sqlDateEnd);
        } else {
            khuyen_maiModel.setThoi_gian_ket_thuc(null);
        }
        int key = khuyen_maiService.edit(khuyen_maiModel);
        if (key > 0) {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công!");
            ressetText();
            ud.doUpdate();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thất Bại!");
        }
    }//GEN-LAST:event_pnl_updateMouseClicked

    private void pnl_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_resetMouseClicked
        ressetText();
    }//GEN-LAST:event_pnl_resetMouseClicked

    private void pnl_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_editMouseClicked
        dispose();
    }//GEN-LAST:event_pnl_editMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel codeKM;
    private javax.swing.JPanel content;
    private javax.swing.JPanel contentKM;
    private com.toedter.calendar.JDateChooser date_Start;
    private com.toedter.calendar.JDateChooser date_end;
    private javax.swing.JPanel header;
    private javax.swing.JPanel idKM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnl_codeKM;
    private javax.swing.JPanel pnl_contentKM;
    private javax.swing.JPanel pnl_edit;
    private javax.swing.JPanel pnl_idKM;
    private javax.swing.JPanel pnl_reset;
    private javax.swing.JPanel pnl_typeKM;
    private javax.swing.JPanel pnl_update;
    private javax.swing.JPanel pnl_valueKM;
    private javax.swing.JRadioButton radio_hetHan;
    private javax.swing.JRadioButton radio_suDung;
    private javax.swing.JTextField txt_inputContent;
    private javax.swing.JTextField txt_inputID;
    private javax.swing.JTextField txt_inputName;
    private javax.swing.JTextField txt_inputValue;
    private javax.swing.JPanel typeKM;
    private javax.swing.JPanel valueKM;
    // End of variables declaration//GEN-END:variables
}
