/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views.JintenalFrame;

import com.QLKS.Service.impl.trang_thai_hoa_donService;
import com.QLKS.model.loai_dich_vuModel;
import com.QLKS.model.trang_thai_hoa_donModel;
import com.QLKS.utils.functionBase;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author steve
 */
public class ITN_trang_thai_hoa_don extends javax.swing.JInternalFrame {

    /**
     * Creates new form ITN_trang_thai_hoa_don
     */
    List<trang_thai_hoa_donModel> list_TTHD;
    trang_thai_hoa_donModel trang_thaiModel;
    trang_thai_hoa_donService trang_thaiService;
    DefaultTableModel dfmTrangThaiHoaDon;
    functionBase funBase;

    public ITN_trang_thai_hoa_don() {
        initComponents();
        trang_thaiModel = new trang_thai_hoa_donModel();
        trang_thaiService = new trang_thai_hoa_donService();
        dfmTrangThaiHoaDon = new DefaultTableModel();
        funBase = new functionBase();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu_icon = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jpnLoaiTinhTrang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        txtTenTrangThaiHD = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();
        button_resset = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        button_addTTHD = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        button_updateTTHD = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        button_deleteTTHD = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTTHD = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jlbSearch = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("TRẠNG THÁI HOÁ ĐƠN");

        header.setBackground(new java.awt.Color(8, 13, 23));
        header.setMaximumSize(new java.awt.Dimension(876, 50));
        header.setMinimumSize(new java.awt.Dimension(876, 50));
        header.setPreferredSize(new java.awt.Dimension(876, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 231, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trạng thái hoá đơn");

        menu_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/custom-iconMenu.png"))); // NOI18N
        menu_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_iconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(menu_icon)
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_icon)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        content.setBackground(new java.awt.Color(48, 48, 48));

        jpnLoaiTinhTrang.setBackground(new java.awt.Color(48, 48, 48));
        jpnLoaiTinhTrang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Loại trạng thái", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 20), new java.awt.Color(154, 231, 246))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(154, 231, 246));
        jLabel2.setText("ID:");
        jLabel2.setMaximumSize(new java.awt.Dimension(16, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(16, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(16, 30));

        lblID.setForeground(new java.awt.Color(154, 231, 246));
        lblID.setText("...");
        lblID.setMaximumSize(new java.awt.Dimension(12, 30));
        lblID.setMinimumSize(new java.awt.Dimension(12, 30));
        lblID.setPreferredSize(new java.awt.Dimension(12, 30));

        jlbName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbName.setForeground(new java.awt.Color(154, 231, 246));
        jlbName.setText("Tên Loại trạng thái :");
        jlbName.setMaximumSize(new java.awt.Dimension(112, 30));
        jlbName.setMinimumSize(new java.awt.Dimension(112, 30));
        jlbName.setPreferredSize(new java.awt.Dimension(112, 30));

        txtTenTrangThaiHD.setBackground(new java.awt.Color(32, 32, 32));
        txtTenTrangThaiHD.setColumns(5);
        txtTenTrangThaiHD.setForeground(new java.awt.Color(154, 231, 246));
        txtTenTrangThaiHD.setMinimumSize(new java.awt.Dimension(46, 30));
        txtTenTrangThaiHD.setPreferredSize(new java.awt.Dimension(46, 30));
        txtTenTrangThaiHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTrangThaiHDActionPerformed(evt);
            }
        });

        lblResult.setForeground(new java.awt.Color(248, 13, 33));

        button_resset.setBackground(new java.awt.Color(36, 36, 36));
        button_resset.setPreferredSize(new java.awt.Dimension(100, 50));
        button_resset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_ressetMouseClicked(evt);
            }
        });
        button_resset.setLayout(new java.awt.BorderLayout());

        jLabel4.setForeground(new java.awt.Color(154, 231, 246));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Làm mới");
        button_resset.add(jLabel4, java.awt.BorderLayout.CENTER);

        button_addTTHD.setBackground(new java.awt.Color(36, 36, 36));
        button_addTTHD.setPreferredSize(new java.awt.Dimension(100, 50));
        button_addTTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_addTTHDMouseClicked(evt);
            }
        });
        button_addTTHD.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(154, 231, 246));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thêm mới");
        button_addTTHD.add(jLabel5, java.awt.BorderLayout.CENTER);

        button_updateTTHD.setBackground(new java.awt.Color(36, 36, 36));
        button_updateTTHD.setPreferredSize(new java.awt.Dimension(100, 50));
        button_updateTTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_updateTTHDMouseClicked(evt);
            }
        });
        button_updateTTHD.setLayout(new java.awt.BorderLayout());

        jLabel6.setForeground(new java.awt.Color(154, 231, 246));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cập nhật");
        button_updateTTHD.add(jLabel6, java.awt.BorderLayout.CENTER);

        button_deleteTTHD.setBackground(new java.awt.Color(36, 36, 36));
        button_deleteTTHD.setPreferredSize(new java.awt.Dimension(100, 50));
        button_deleteTTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_deleteTTHDMouseClicked(evt);
            }
        });
        button_deleteTTHD.setLayout(new java.awt.BorderLayout());

        jLabel7.setForeground(new java.awt.Color(154, 231, 246));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Xoá");
        button_deleteTTHD.add(jLabel7, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jpnLoaiTinhTrangLayout = new javax.swing.GroupLayout(jpnLoaiTinhTrang);
        jpnLoaiTinhTrang.setLayout(jpnLoaiTinhTrangLayout);
        jpnLoaiTinhTrangLayout.setHorizontalGroup(
            jpnLoaiTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoaiTinhTrangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnLoaiTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoaiTinhTrangLayout.createSequentialGroup()
                        .addComponent(button_resset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_addTTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_updateTTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_deleteTTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnLoaiTinhTrangLayout.createSequentialGroup()
                        .addGroup(jpnLoaiTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnLoaiTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenTrangThaiHD, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(204, 204, 204))))
        );
        jpnLoaiTinhTrangLayout.setVerticalGroup(
            jpnLoaiTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoaiTinhTrangLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpnLoaiTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jpnLoaiTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnLoaiTinhTrangLayout.createSequentialGroup()
                        .addComponent(lblResult)
                        .addGap(133, 133, 133))
                    .addGroup(jpnLoaiTinhTrangLayout.createSequentialGroup()
                        .addGroup(jpnLoaiTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenTrangThaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jpnLoaiTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_resset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_updateTTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_addTTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_deleteTTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(48, 48, 48));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblTTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTTHD);

        txtSearch.setBackground(new java.awt.Color(32, 32, 32));
        txtSearch.setForeground(new java.awt.Color(154, 231, 246));

        jlbSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbSearch.setForeground(new java.awt.Color(154, 231, 246));
        jlbSearch.setText("Nhập trạng thái hoá đơn:");

        jPanel3.setBackground(new java.awt.Color(32, 32, 32));
        jPanel3.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(32, 32, 32));
        jLabel3.setForeground(new java.awt.Color(154, 231, 246));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tìm kiếm");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlbSearch)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbSearch)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnLoaiTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnLoaiTinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1139, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ressetText() {
        lblID.setText("");
        txtTenTrangThaiHD.setText("");
    }

    public void loadData() {
        Object[] columnNames = {"STT", "Mã Loại Dịch Vụ", "Tên loại dịch vụ", ""};
//        if (nameSeaechInput != null) {
//            dfmThietBi = thiet_biService.search(nameSeaechInput);
//        } else {
//            dfmThietBi = cauhinhDAO.getAll();
//        }
        list_TTHD = trang_thaiService.findAll();

        dfmTrangThaiHoaDon = new DefaultTableModel(new Object[0][0], columnNames);
        int index = 1;
        for (trang_thai_hoa_donModel adv : list_TTHD) {
            Object[] o = new Object[4];
            o[0] = index;
            o[1] = adv.getId();
            o[2] = adv.getName();
            dfmTrangThaiHoaDon.addRow(o);
            index++;
        }
        tblTTHD.setModel(dfmTrangThaiHoaDon);
        funBase.addCheckBox(3, tblTTHD);

        // Cài đặt sự kiện khi click từng dòng trong bảng
        if (list_TTHD.size() > 0) {
            tblTTHD.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    int currentRow = tblTTHD.getSelectedRow();
                    if (currentRow < 0) {
                        currentRow = 0;
                    }
                    // Chèn dữ liệu lên form
                    if (currentRow >= 0) {
                        lblID.setText(tblTTHD.getValueAt(currentRow, 1).toString());
                        txtTenTrangThaiHD.setText(tblTTHD.getValueAt(currentRow, 2).toString());
                    }
                }
            });
        }
    }
    private void menu_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseClicked

    }//GEN-LAST:event_menu_iconMouseClicked

    private void menu_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseEntered

    }//GEN-LAST:event_menu_iconMouseEntered

    private void menu_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseExited

    }//GEN-LAST:event_menu_iconMouseExited

    private void txtTenTrangThaiHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTrangThaiHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTrangThaiHDActionPerformed

    private void button_addTTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_addTTHDMouseClicked
        String name = txtTenTrangThaiHD.getText();
        boolean check_TTHD = true;
        if (name.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống!");
            check_TTHD = false;
        }
        if (check_TTHD == true) {
            trang_thai_hoa_donModel getNameTT = trang_thaiService.findByName(name);
            if (getNameTT == null) {
                trang_thaiModel.setName(name);
                Long key = trang_thaiService.add_TTHD(trang_thaiModel);
                if (key > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thành Công!");
                    ressetText();
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thất Bại!");
                    loadData();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã tồn tại!");
            }
        }
    }//GEN-LAST:event_button_addTTHDMouseClicked

    private void button_ressetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ressetMouseClicked
        ressetText();
        loadData();
    }//GEN-LAST:event_button_ressetMouseClicked

    private void button_updateTTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_updateTTHDMouseClicked
        Long idTTHD = Long.parseLong(lblID.getText());
        String nameTTHD = txtTenTrangThaiHD.getText();
        boolean check_TTHD = true;
        if (nameTTHD.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống!");
            check_TTHD = false;
        }

        if (check_TTHD == true) {
            trang_thaiModel.setId(idTTHD);
            trang_thaiModel.setName(nameTTHD);
            int key = trang_thaiService.edit(trang_thaiModel);
            if (key > 0) {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công");
                ressetText();
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thất Bại!");
                loadData();
            }
        }
    }//GEN-LAST:event_button_updateTTHDMouseClicked

    private void button_deleteTTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_deleteTTHDMouseClicked
          String succesDeltete = "";
        String errDeltete = "";
        boolean check_del = false;

        int thongBao = JOptionPane.showConfirmDialog(this, "Bạn có chắc không?", "Thông báo!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (thongBao == JOptionPane.YES_OPTION) {

            for (int i = 0; i < tblTTHD.getRowCount(); i++) {
                if (funBase.IsSelected(i, 3, tblTTHD)) {
                    check_del = true;
                    int rowSuccess = trang_thaiService.delete(Long.parseLong(tblTTHD.getValueAt(i, 1).toString()));
                    tblTTHD.clearSelection();
                    if (rowSuccess > 0) {
                        succesDeltete += "\t" + tblTTHD.getValueAt(i, 2).toString() + "\n";
                    } else {
                        errDeltete += "\t" + tblTTHD.getValueAt(i, 2).toString() + "\n";
                    }
                }
            }
            ressetText();
            loadData();
            if (check_del == true) {
                String mess = "";
                if (succesDeltete.length() > 0) {
                    mess += "Bạn đã xóa thành công: \n" + succesDeltete;

                }
                if (errDeltete.length() > 0) {
                    mess += "Không thể xóa: \n" + errDeltete;
                }
                JOptionPane.showMessageDialog(rootPane, mess, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hàng để xóa", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_button_deleteTTHDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button_addTTHD;
    private javax.swing.JPanel button_deleteTTHD;
    private javax.swing.JPanel button_resset;
    private javax.swing.JPanel button_updateTTHD;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbSearch;
    private javax.swing.JPanel jpnLoaiTinhTrang;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel menu_icon;
    private javax.swing.JTable tblTTHD;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenTrangThaiHD;
    // End of variables declaration//GEN-END:variables
}
