/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views.JintenalFrame;

import com.QLKS.Service.impl.hoa_donService;
import com.QLKS.Service.impl.phongService;
import com.QLKS.model.hoa_donModel;
import com.QLKS.model.phongModel;
import com.QLKS.utils.CustomButtonClumnJTable;
import com.QLKS.utils.functionBase;
import com.QLKS.views.JintenalFrame.action.ITN_add_khachhang;
import com.QLKS.views.JintenalFrame.action.ITN_edit_khachhang;
import static com.QLKS.views.mainFrame.changeColor;
import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author steve
 */
public class ITN_quan_ly_hoadon extends javax.swing.JInternalFrame implements ITN_thanh_toan_hoa_don.CallbackCheckout{

    private ITN_add_khachhang ITN_add_khachhang;
    private ITN_edit_khachhang ITN_edit_khachhang;

    /**
     * Creates new form ITN_quan_ly
     */
    hoa_donModel hoa_donModel;
    hoa_donService hoa_donService;
    DefaultTableModel dfmHoaDon;
    functionBase funBase;
    List<hoa_donModel> listHoaDon;
    phongModel phongModel;
    phongService phongService;
    private JDesktopPane jdek;

    public ITN_quan_ly_hoadon() {
        initComponents();
        hoa_donModel = new hoa_donModel();
        hoa_donService = new hoa_donService();
        dfmHoaDon = new DefaultTableModel();
        funBase = new functionBase();
        phongModel = new phongModel();
        phongService = new phongService();
        loadData();

    }

    public void changeimage(JLabel btn, String resourceImage) {
        ImageIcon a = new ImageIcon(getClass().getResource(resourceImage));
        btn.setIcon(a);
    }

    public void centerJIF(JInternalFrame jif) {
        Dimension desktopSize = jdek.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }

    public void showInternalFrame(JInternalFrame jif) {
        if (!jif.isVisible()) {
            jdek = getDesktopPane();
            jdek.add(jif);
            centerJIF(jif);
            jif.setVisible(true);       
            jdek.show();
        }
    }

    public void loadData() {
        Object[] columnNames = {"STT", "Mã Hóa Đơn", "Tên Khách Hàng", "CMND", "Phòng", "Loại Phòng", "Trạng Thái Hóa Đơn", "Tổng Tiền", "", ""};
//        if (nameSeaechInput != null) {
//            dfmThietBi = thiet_biService.search(nameSeaechInput);
//        } else {
//            dfmThietBi = cauhinhDAO.getAll();
//        }
        listHoaDon = hoa_donService.findAll();

        dfmHoaDon = new DefaultTableModel(new Object[0][0], columnNames);
        int index = 1;
        for (hoa_donModel adv : listHoaDon) {
            phongModel = phongService.findOne(adv.getId_P());
            Object[] o = new Object[10];
            o[0] = index;
            o[1] = adv.getId();
            o[2] = adv.getKhach_hang().getName();
            o[3] = adv.getKhach_hang().getIdentityCard();
            o[4] = adv.getId_P();
            o[5] = phongModel.getLoai_phong().getName_LP();
            o[6] = adv.getTrang_thaiHD().getName();
            o[7] = funBase.formatTien(adv.getThanh_tien());
            o[9] = "Thanh Toán";
            dfmHoaDon.addRow(o);
            index++;
        }
        tbl_HoaDon.setModel(dfmHoaDon);
        funBase.addCheckBox(8, tbl_HoaDon);
        new CustomButtonClumnJTable(tbl_HoaDon, 9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        button_search_KH = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        line_button_click3 = new javax.swing.JLabel();
        line_button4 = new javax.swing.JPanel();
        custom_line4 = new javax.swing.JLabel();
        button_refesh_KH = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        line_button_click4 = new javax.swing.JLabel();
        button_refesh_KH1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        line_button_click5 = new javax.swing.JLabel();
        line_button5 = new javax.swing.JPanel();
        custom_line5 = new javax.swing.JLabel();
        line_button6 = new javax.swing.JPanel();
        custom_line6 = new javax.swing.JLabel();
        button_refesh_KH2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        line_button_click6 = new javax.swing.JLabel();
        button_refesh_KH3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        line_button_click7 = new javax.swing.JLabel();
        custom_line7 = new javax.swing.JLabel();
        line_button7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        add_dsktop_pnl = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDon = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        header.setBackground(new java.awt.Color(16, 14, 17));
        header.setMaximumSize(new java.awt.Dimension(876, 50));
        header.setMinimumSize(new java.awt.Dimension(876, 50));
        header.setPreferredSize(new java.awt.Dimension(876, 50));
        header.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 231, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý hoá đơn");
        header.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(16, 14, 17));
        menu.setMaximumSize(new java.awt.Dimension(150, 604));
        menu.setMinimumSize(new java.awt.Dimension(150, 604));
        menu.setPreferredSize(new java.awt.Dimension(150, 604));

        button_search_KH.setBackground(new java.awt.Color(27, 27, 27));
        button_search_KH.setMaximumSize(new java.awt.Dimension(150, 40));
        button_search_KH.setMinimumSize(new java.awt.Dimension(150, 40));
        button_search_KH.setPreferredSize(new java.awt.Dimension(150, 40));
        button_search_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_search_KHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_search_KHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_search_KHMouseExited(evt);
            }
        });
        button_search_KH.setLayout(new java.awt.BorderLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/icons8_search_20px.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(40, 40));
        button_search_KH.add(jLabel10, java.awt.BorderLayout.LINE_START);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(154, 231, 246));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tìm Kiếm");
        button_search_KH.add(jLabel11, java.awt.BorderLayout.CENTER);

        line_button_click3.setBackground(new java.awt.Color(0, 0, 0));
        line_button_click3.setPreferredSize(new java.awt.Dimension(5, 40));
        button_search_KH.add(line_button_click3, java.awt.BorderLayout.LINE_END);

        menu.add(button_search_KH);

        line_button4.setBackground(new java.awt.Color(0, 0, 0));
        line_button4.setMaximumSize(new java.awt.Dimension(150, 5));
        line_button4.setLayout(new java.awt.BorderLayout());

        custom_line4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custom_line4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/custom-lineJinternal.png"))); // NOI18N
        line_button4.add(custom_line4, java.awt.BorderLayout.CENTER);

        menu.add(line_button4);

        button_refesh_KH.setBackground(new java.awt.Color(27, 27, 27));
        button_refesh_KH.setMaximumSize(new java.awt.Dimension(150, 40));
        button_refesh_KH.setMinimumSize(new java.awt.Dimension(150, 40));
        button_refesh_KH.setPreferredSize(new java.awt.Dimension(150, 40));
        button_refesh_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_refesh_KHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_refesh_KHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_refesh_KHMouseExited(evt);
            }
        });
        button_refesh_KH.setLayout(new java.awt.BorderLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/icons8_update_left_rotation_20px.png"))); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(40, 40));
        button_refesh_KH.add(jLabel12, java.awt.BorderLayout.LINE_START);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(154, 231, 246));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cập Nhật");
        button_refesh_KH.add(jLabel13, java.awt.BorderLayout.CENTER);

        line_button_click4.setBackground(new java.awt.Color(0, 0, 0));
        line_button_click4.setPreferredSize(new java.awt.Dimension(5, 40));
        button_refesh_KH.add(line_button_click4, java.awt.BorderLayout.LINE_END);

        button_refesh_KH1.setBackground(new java.awt.Color(27, 27, 27));
        button_refesh_KH1.setMaximumSize(new java.awt.Dimension(150, 40));
        button_refesh_KH1.setMinimumSize(new java.awt.Dimension(150, 40));
        button_refesh_KH1.setPreferredSize(new java.awt.Dimension(150, 40));
        button_refesh_KH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_refesh_KH1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_refesh_KH1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_refesh_KH1MouseExited(evt);
            }
        });
        button_refesh_KH1.setLayout(new java.awt.BorderLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/icons8_update_left_rotation_20px.png"))); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(40, 40));
        button_refesh_KH1.add(jLabel14, java.awt.BorderLayout.LINE_START);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(154, 231, 246));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cập Nhật");
        button_refesh_KH1.add(jLabel15, java.awt.BorderLayout.CENTER);

        line_button_click5.setBackground(new java.awt.Color(0, 0, 0));
        line_button_click5.setPreferredSize(new java.awt.Dimension(5, 40));
        button_refesh_KH1.add(line_button_click5, java.awt.BorderLayout.LINE_END);

        button_refesh_KH.add(button_refesh_KH1, java.awt.BorderLayout.PAGE_START);

        line_button5.setBackground(new java.awt.Color(0, 0, 0));
        line_button5.setMaximumSize(new java.awt.Dimension(150, 5));
        line_button5.setLayout(new java.awt.BorderLayout());

        custom_line5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custom_line5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/custom-lineJinternal.png"))); // NOI18N
        line_button5.add(custom_line5, java.awt.BorderLayout.CENTER);

        button_refesh_KH.add(line_button5, java.awt.BorderLayout.PAGE_END);

        menu.add(button_refesh_KH);

        line_button6.setBackground(new java.awt.Color(0, 0, 0));
        line_button6.setMaximumSize(new java.awt.Dimension(150, 5));
        line_button6.setLayout(new java.awt.BorderLayout());

        custom_line6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custom_line6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/custom-lineJinternal.png"))); // NOI18N
        line_button6.add(custom_line6, java.awt.BorderLayout.CENTER);

        menu.add(line_button6);

        button_refesh_KH2.setBackground(new java.awt.Color(27, 27, 27));
        button_refesh_KH2.setMaximumSize(new java.awt.Dimension(150, 40));
        button_refesh_KH2.setMinimumSize(new java.awt.Dimension(150, 40));
        button_refesh_KH2.setPreferredSize(new java.awt.Dimension(150, 40));
        button_refesh_KH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_refesh_KH2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_refesh_KH2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_refesh_KH2MouseExited(evt);
            }
        });
        button_refesh_KH2.setLayout(new java.awt.BorderLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/icons8_food_service_20px_2.png"))); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(40, 40));
        button_refesh_KH2.add(jLabel16, java.awt.BorderLayout.LINE_START);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(154, 231, 246));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Thêm Dịch Vụ");
        button_refesh_KH2.add(jLabel17, java.awt.BorderLayout.CENTER);

        line_button_click6.setBackground(new java.awt.Color(0, 0, 0));
        line_button_click6.setPreferredSize(new java.awt.Dimension(5, 40));
        button_refesh_KH2.add(line_button_click6, java.awt.BorderLayout.LINE_END);

        menu.add(button_refesh_KH2);

        button_refesh_KH3.setBackground(new java.awt.Color(27, 27, 27));
        button_refesh_KH3.setMaximumSize(new java.awt.Dimension(150, 40));
        button_refesh_KH3.setMinimumSize(new java.awt.Dimension(150, 40));
        button_refesh_KH3.setPreferredSize(new java.awt.Dimension(150, 40));
        button_refesh_KH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_refesh_KH3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_refesh_KH3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_refesh_KH3MouseExited(evt);
            }
        });
        button_refesh_KH3.setLayout(new java.awt.BorderLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/icons8_wallet_20px.png"))); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(40, 40));
        button_refesh_KH3.add(jLabel18, java.awt.BorderLayout.LINE_START);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(154, 231, 246));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Chi Tiết HĐ");
        button_refesh_KH3.add(jLabel19, java.awt.BorderLayout.CENTER);

        line_button_click7.setBackground(new java.awt.Color(0, 0, 0));
        line_button_click7.setPreferredSize(new java.awt.Dimension(5, 40));
        button_refesh_KH3.add(line_button_click7, java.awt.BorderLayout.LINE_END);

        custom_line7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custom_line7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/custom-lineJinternal.png"))); // NOI18N
        button_refesh_KH3.add(custom_line7, java.awt.BorderLayout.PAGE_START);

        menu.add(button_refesh_KH3);

        line_button7.setBackground(new java.awt.Color(0, 0, 0));
        line_button7.setMaximumSize(new java.awt.Dimension(150, 5));
        line_button7.setLayout(new java.awt.BorderLayout());
        menu.add(line_button7);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        add_dsktop_pnl.setBackground(new java.awt.Color(238, 238, 238));
        add_dsktop_pnl.setLayout(new java.awt.BorderLayout());

        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_HoaDon);

        add_dsktop_pnl.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(add_dsktop_pnl, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_search_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_search_KHMouseClicked
    }//GEN-LAST:event_button_search_KHMouseClicked

    private void button_search_KHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_search_KHMouseEntered
        changeColor(button_search_KH, new Color(0, 0, 0));
    }//GEN-LAST:event_button_search_KHMouseEntered

    private void button_search_KHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_search_KHMouseExited
        changeColor(button_search_KH, new Color(8, 13, 21));
    }//GEN-LAST:event_button_search_KHMouseExited

    private void button_refesh_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KHMouseClicked
        changeimage(custom_line4, "/com/QLKS/icon/icon_button/line_custom_hover_jinternal.png");
    }//GEN-LAST:event_button_refesh_KHMouseClicked

    private void button_refesh_KHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KHMouseEntered
        changeColor(button_refesh_KH, new Color(0, 0, 0));
    }//GEN-LAST:event_button_refesh_KHMouseEntered

    private void button_refesh_KHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KHMouseExited
        changeColor(button_refesh_KH, new Color(8, 13, 21));
        changeimage(custom_line4, "/com/QLKS/icon/icon_button/custom-lineJinternal.png");
    }//GEN-LAST:event_button_refesh_KHMouseExited

    private void button_refesh_KH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KH1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_refesh_KH1MouseClicked

    private void button_refesh_KH1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KH1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button_refesh_KH1MouseEntered

    private void button_refesh_KH1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KH1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button_refesh_KH1MouseExited

    private void button_refesh_KH2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KH2MouseClicked
        ITN_quan_ly_dich_vuPhong ITNQLDVP = new ITN_quan_ly_dich_vuPhong();
        showInternalFrame(ITNQLDVP);
    }//GEN-LAST:event_button_refesh_KH2MouseClicked

    private void button_refesh_KH2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KH2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button_refesh_KH2MouseEntered

    private void button_refesh_KH2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KH2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button_refesh_KH2MouseExited

    private void tbl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDonMouseClicked
        int currentRow = tbl_HoaDon.getSelectedRow();
        int currentColumns = tbl_HoaDon.getSelectedColumn();
        if (currentRow >= 0 && currentColumns == 9) {
            String trang_thaiHD = dfmHoaDon.getValueAt(currentRow, 6).toString();
            if (trang_thaiHD.equals("Chưa Thanh Toán")) {
                String cmndKH = dfmHoaDon.getValueAt(currentRow, 3).toString();
                showInternalFrame(new ITN_thanh_toan_hoa_don(this,cmndKH));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Khách hàng này đã thanh toán hoặc chưa nhận phòng. Không thể thêm dịch vụ cho khách hàng này !", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tbl_HoaDonMouseClicked

    private void button_refesh_KH3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KH3MouseClicked
        int columnRow = tbl_HoaDon.getSelectedRow();
        if (columnRow >= 0) {
            Long idHoaDon = Long.parseLong(dfmHoaDon.getValueAt(columnRow, 1).toString());
            showInternalFrame(new ITN_Chi_Tiet_Hoa_Don_View(idHoaDon));
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hàng để xem chi tiết hóa đơn", "Thông báo", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_button_refesh_KH3MouseClicked

    private void button_refesh_KH3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KH3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button_refesh_KH3MouseEntered

    private void button_refesh_KH3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_refesh_KH3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button_refesh_KH3MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane add_dsktop_pnl;
    private javax.swing.JPanel button_refesh_KH;
    private javax.swing.JPanel button_refesh_KH1;
    private javax.swing.JPanel button_refesh_KH2;
    private javax.swing.JPanel button_refesh_KH3;
    private javax.swing.JPanel button_search_KH;
    private javax.swing.JLabel custom_line4;
    private javax.swing.JLabel custom_line5;
    private javax.swing.JLabel custom_line6;
    private javax.swing.JLabel custom_line7;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel line_button4;
    private javax.swing.JPanel line_button5;
    private javax.swing.JPanel line_button6;
    private javax.swing.JPanel line_button7;
    private javax.swing.JLabel line_button_click3;
    private javax.swing.JLabel line_button_click4;
    private javax.swing.JLabel line_button_click5;
    private javax.swing.JLabel line_button_click6;
    private javax.swing.JLabel line_button_click7;
    private javax.swing.JPanel menu;
    private javax.swing.JTable tbl_HoaDon;
    // End of variables declaration//GEN-END:variables

    @Override
    public void doCheckOut() {
       loadData();
    }
}
