/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views.JintenalFrame;

import com.QLKS.Service.impl.dich_vuService;
import com.QLKS.Service.impl.hoa_donService;
import com.QLKS.Service.impl.su_dung_dich_vuService;
import com.QLKS.model.dich_vuModel;
import com.QLKS.model.hoa_donModel;
import com.QLKS.model.su_dung_dich_vuModel;
import com.QLKS.utils.functionBase;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author steve
 */
public class ITN_Sudungdichvu extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sudungdichvu
     */
    hoa_donModel hoa_donModel;
    su_dung_dich_vuModel su_dungDVModel;
    dich_vuModel dich_vuModel;
    DefaultTableModel dfmDichVu;
    DefaultTableModel dfmSDDV;
    DefaultComboBoxModel<dich_vuModel> cbxDichVu;
    dich_vuService dich_vuService;
    su_dung_dich_vuService su_dungService;
    hoa_donService hoa_donService;
    List<dich_vuModel> listDV;
    List<su_dung_dich_vuModel> listSDDV;
    functionBase funBase;

    public ITN_Sudungdichvu(String id_P, String ten_KH) {
        initComponents();
        hoa_donService = new hoa_donService();
        hoa_donModel = new hoa_donModel();
        su_dungDVModel = new su_dung_dich_vuModel();
        dich_vuModel = new dich_vuModel();
        dfmDichVu = new DefaultTableModel();
        dfmSDDV = new DefaultTableModel();
        cbxDichVu = new DefaultComboBoxModel();
        dich_vuService = new dich_vuService();
        su_dungService = new su_dung_dich_vuService();
        funBase = new functionBase();
        lblMaPhong.setText(id_P);
        lblTenKhachHang.setText(ten_KH);
        listDV = dich_vuService.findAll();

        loadDataDV();
        loadDataSDDV();

    }

    public void loadDataDV() {
        Object[] columnNames = {"STT", "Mã Dịch Vụ", "Tên Loại DV", "Đơn Vị", "Giá"};
//        if (nameSeaechInput != null) {
//            dfmThietBi = thiet_biService.search(nameSeaechInput);
//        } else {
//            dfmThietBi = cauhinhDAO.getAll();
//        }

        dfmDichVu = new DefaultTableModel(new Object[0][0], columnNames);
        int index = 1;
        for (dich_vuModel adv : listDV) {
            cbxDichVu.addElement(adv);
            Object[] o = new Object[6];
            o[0] = index;
            o[1] = adv.getId();
            o[2] = adv.getLoai_dich_vuModel().getName();
            o[3] = adv.getDon_viModel().getName_DV();
            o[4] = adv.getPrice();
            dfmDichVu.addRow(o);
            index++;
        }
        tblDichVu.setModel(dfmDichVu);
        comboDichVu.setModel(cbxDichVu);
    }

    public void loadDataSDDV() {
        Object[] columnNames = {"STT", "Mã Sử Dụng DV", "Mã Dịch Vụ", "Tên Loại DV", "Đơn Vị", "Số Lượng", "Tổng Tiền", ""};
//        if (nameSeaechInput != null) {
//            dfmThietBi = thiet_biService.search(nameSeaechInput);
//        } else {
//            dfmThietBi = cauhinhDAO.getAll();
//        }
        String idPhong = lblMaPhong.getText();
        listSDDV = su_dungService.findAll();
        su_dung_dich_vuModel getIdPDV = su_dungService.findByIdP(idPhong);
        dfmSDDV = new DefaultTableModel(new Object[0][0], columnNames);
        int index = 1;
        if (getIdPDV != null) {
            for (su_dung_dich_vuModel adv : listSDDV) {

                dich_vuModel = dich_vuService.findOne(adv.getId_DV());
                Object[] o = new Object[7];
                o[0] = index;
                o[1] = adv.getId();
                o[2] = adv.getId_DV();
                o[3] = dich_vuModel.getLoai_dich_vuModel().getName();
                o[4] = dich_vuModel.getDon_viModel().getName_DV();
                o[5] = adv.getAmount();
                o[6] = (adv.getAmount() * dich_vuModel.getPrice());
                dfmSDDV.addRow(o);
                index++;
            }
        }

        tblDichVuDaSD.setModel(dfmSDDV);
        funBase.addCheckBox(7, tblDichVuDaSD);

    }

    public void ressetText() {
        txt_IDSDDV.setText("");
        txtSoLuong.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboDichVu = new javax.swing.JComboBox<>();
        txtErrorMaSDDichVu = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JSpinner();
        txtErrorSoLuong = new javax.swing.JLabel();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnHuyBo = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        txt_IDSDDV = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMaPhong = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTenKhachHang = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDichVuDaSD = new javax.swing.JTable();

        setBackground(new java.awt.Color(48, 48, 48));
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(1000, 812));

        jPanel1.setBackground(new java.awt.Color(48, 48, 48));
        jPanel1.setForeground(new java.awt.Color(154, 231, 246));

        jLabel7.setBackground(new java.awt.Color(8, 18, 28));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(154, 231, 246));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("THÊM MỚI DỊCH VỤ ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(154, 231, 246));
        jLabel8.setText("Mã sử dụng dịch vụ:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(154, 231, 246));
        jLabel9.setText("Tên dịch vụ:");

        txtErrorMaSDDichVu.setForeground(new java.awt.Color(255, 0, 51));
        txtErrorMaSDDichVu.setText("...");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(154, 231, 246));
        jLabel11.setText("Số lượng:");

        txtErrorSoLuong.setForeground(new java.awt.Color(255, 51, 51));
        txtErrorSoLuong.setText("...");

        btnThemMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMoiMouseClicked(evt);
            }
        });
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapNhatMouseClicked(evt);
            }
        });
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnHuyBo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseClicked(evt);
            }
        });
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        txt_IDSDDV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_IDSDDV.setForeground(new java.awt.Color(154, 231, 246));
        txt_IDSDDV.setText("...");
        txt_IDSDDV.setToolTipText("");
        txt_IDSDDV.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(btnHuyBo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtErrorMaSDDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtErrorSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addComponent(comboDichVu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txt_IDSDDV, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnThemMoi))))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_IDSDDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorMaSDDichVu)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorSoLuong)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(48, 48, 48));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(154, 231, 246))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(600, 266));

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDichVu);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(48, 48, 48));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phòng-khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(154, 231, 246))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 231, 246));
        jLabel1.setText("Mã Phòng");

        lblMaPhong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMaPhong.setForeground(new java.awt.Color(154, 231, 246));
        lblMaPhong.setText("...");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(154, 231, 246));
        jLabel5.setText("Tên khách hàng:");

        lblTenKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTenKhachHang.setForeground(new java.awt.Color(154, 231, 246));
        lblTenKhachHang.setText("....");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(lblTenKhachHang)
                    .addComponent(lblMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(48, 48, 48));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách dịch vụ đã sử dụng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(154, 231, 246))); // NOI18N

        tblDichVuDaSD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDichVuDaSD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDichVuDaSDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDichVuDaSD);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed

    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        dispose();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed

    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDichVuMouseClicked
        int pos = tblDichVu.getSelectedRow();
        Long maDV = listDV.get(pos).getId();
        dich_vuModel dv = listDV.stream().filter(x -> x.getId().equals(maDV)).findAny().orElse(null);
        cbxDichVu.setSelectedItem(dv);
    }//GEN-LAST:event_tblDichVuMouseClicked

    private void tblDichVuDaSDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDichVuDaSDMouseClicked
        int pob = tblDichVuDaSD.getSelectedRow();
        String maSDDV = dfmSDDV.getValueAt(pob, 1).toString();
        txt_IDSDDV.setText(maSDDV);
        Long maDV = Long.parseLong(dfmSDDV.getValueAt(pob, 2).toString());
        dich_vuModel ssdv = listDV.stream().filter(x -> x.getId().equals(maDV)).findAny().orElse(null);
        int soLuong = Integer.parseInt(dfmSDDV.getValueAt(pob, 5).toString());
        txtSoLuong.setValue(soLuong);
        cbxDichVu.setSelectedItem(ssdv);

    }//GEN-LAST:event_tblDichVuDaSDMouseClicked

    private void btnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseClicked
        txt_IDSDDV.setText("");
        txtSoLuong.setValue(0);
    }//GEN-LAST:event_btnLamMoiMouseClicked

    private void btnThemMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMoiMouseClicked
        dich_vuModel dichVuId = (dich_vuModel) cbxDichVu.getSelectedItem();
        String idPhong = lblMaPhong.getText();
        String tenKH = lblTenKhachHang.getText();
        int soLuongSDDV = (int) txtSoLuong.getValue();
        Long idDV = dichVuId.getId();
        su_dungDVModel.setId_DV(idDV);
        su_dungDVModel.setAmount(soLuongSDDV);
        su_dungDVModel.setId_P(idPhong);
        su_dung_dich_vuModel getResultDV = su_dungService.add(su_dungDVModel);
        Date soNgayTT = new Date();
        java.sql.Date ngayTraTT = new java.sql.Date(soNgayTT.getTime());
        if (getResultDV != null) {
            loadDataDV();
            loadDataSDDV();
            ressetText();
            tblDichVuDaSD.setRowSelectionInterval(tblDichVuDaSD.getRowCount() - 1, tblDichVuDaSD.getRowCount() - 1);
            int pob = tblDichVuDaSD.getSelectedRow();
            float tien_dich_vu = Float.parseFloat(dfmSDDV.getValueAt(pob, 6).toString());
            hoa_donModel findHoaDonByPhong = hoa_donService.findByPhong(idPhong);
            if (findHoaDonByPhong != null) {
                Float tongTien = (findHoaDonByPhong.getTien_phong() * findHoaDonByPhong.getSo_ngay()) + tien_dich_vu + (findHoaDonByPhong.getTien_phong() * findHoaDonByPhong.getPhu_phi()) - findHoaDonByPhong.getGiam_giaKH();
                hoa_donModel.setId(findHoaDonByPhong.getId());
                hoa_donModel.setId_KH(findHoaDonByPhong.getId_KH());
                hoa_donModel.setId_P(findHoaDonByPhong.getId_P());
                hoa_donModel.setId_TTHD(findHoaDonByPhong.getId_TTHD());
                hoa_donModel.setId_SDDV(getResultDV.getId());
                hoa_donModel.setHinh_thucTT(findHoaDonByPhong.getHinh_thucTT());
                hoa_donModel.setPhu_phi(findHoaDonByPhong.getPhu_phi());
                hoa_donModel.setTien_phong(findHoaDonByPhong.getTien_phong());
                hoa_donModel.setTien_dich_vu(tien_dich_vu);
                hoa_donModel.setGiam_giaKH(findHoaDonByPhong.getGiam_giaKH());
                hoa_donModel.setSo_ngay(findHoaDonByPhong.getSo_ngay());
                hoa_donModel.setThanh_tien(tongTien);
                hoa_donModel.setSo_ngay_thuc_te(ngayTraTT);
                hoa_donModel.setSo_ngay_du_kien(findHoaDonByPhong.getSo_ngay_du_kien());
                hoa_donModel.setNgay_den_thuc_te(findHoaDonByPhong.getNgay_den_thuc_te());
                hoa_donModel.setNgay_den_du_kien(findHoaDonByPhong.getNgay_den_du_kien());

                int key = hoa_donService.edit(hoa_donModel);
                if (key > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm Thành Công!");
                    loadDataDV();
                    loadDataSDDV();
                    ressetText();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Thất Bại!");
            }
        }
    }//GEN-LAST:event_btnThemMoiMouseClicked

    private void btnCapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatMouseClicked
        Date soNgayTT = new Date();
        java.sql.Date ngayTraTT = new java.sql.Date(soNgayTT.getTime());
        String idPhong = lblMaPhong.getText();
        Long idMSD = Long.parseLong(txt_IDSDDV.getText().toString());
        dich_vuModel idDV = (dich_vuModel) cbxDichVu.getSelectedItem();
        int soLuong = (int) txtSoLuong.getValue();
        Long getIDDV = idDV.getId();
        su_dung_dich_vuModel sddvModelD = su_dungService.findOne(idMSD);
        if (sddvModelD != null) {
            su_dungDVModel.setId(idMSD);
            su_dungDVModel.setId_DV(getIDDV);
            su_dungDVModel.setAmount(sddvModelD.getAmount() + soLuong);
            int key = su_dungService.edit(su_dungDVModel);
            if (key > 0) {
                su_dung_dich_vuModel getBySDDV = su_dungService.findOne(idMSD);

                loadDataDV();
                loadDataSDDV();
                ressetText();
                float tien_dich_vu = getBySDDV.getAmount() * getBySDDV.getDich_vu().getPrice();
                hoa_donModel findHoaDonByPhong = hoa_donService.findByPhong(idPhong);
                if (findHoaDonByPhong != null) {
                    Float tongTien = (findHoaDonByPhong.getTien_phong() * findHoaDonByPhong.getSo_ngay()) + tien_dich_vu + (findHoaDonByPhong.getTien_phong() * findHoaDonByPhong.getPhu_phi()) - findHoaDonByPhong.getGiam_giaKH();
                    hoa_donModel.setId(findHoaDonByPhong.getId());
                    hoa_donModel.setId_KH(findHoaDonByPhong.getId_KH());
                    hoa_donModel.setId_P(findHoaDonByPhong.getId_P());
                    hoa_donModel.setId_TTHD(findHoaDonByPhong.getId_TTHD());
                    hoa_donModel.setId_SDDV(getBySDDV.getId());
                    hoa_donModel.setHinh_thucTT(findHoaDonByPhong.getHinh_thucTT());
                    hoa_donModel.setPhu_phi(findHoaDonByPhong.getPhu_phi());
                    hoa_donModel.setTien_phong(findHoaDonByPhong.getTien_phong());
                    hoa_donModel.setTien_dich_vu(tien_dich_vu);
                    hoa_donModel.setGiam_giaKH(findHoaDonByPhong.getGiam_giaKH());
                    hoa_donModel.setSo_ngay(findHoaDonByPhong.getSo_ngay());
                    hoa_donModel.setThanh_tien(tongTien);
                    hoa_donModel.setSo_ngay_thuc_te(ngayTraTT);
                    hoa_donModel.setSo_ngay_du_kien(findHoaDonByPhong.getSo_ngay_du_kien());
                    hoa_donModel.setNgay_den_thuc_te(findHoaDonByPhong.getNgay_den_thuc_te());
                    hoa_donModel.setNgay_den_du_kien(findHoaDonByPhong.getNgay_den_du_kien());

                    int keys = hoa_donService.edit(hoa_donModel);
                    if (keys > 0) {
                        JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công!");
                        loadDataDV();
                        loadDataSDDV();
                        ressetText();
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Thất Bại!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thất Bại!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Dịch Vụ này chưa được yêu cầu!");
        }

    }//GEN-LAST:event_btnCapNhatMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        String succesDeltete = "";
        String errDeltete = "";
        Boolean check = false;
        int thongbao = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn không ?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (thongbao == JOptionPane.YES_OPTION) {

            for (int i = 0; i < tblDichVuDaSD.getRowCount(); i++) {
                if (funBase.IsSelected(i, 7, tblDichVuDaSD)) {
                    check = true;

                    int rowSucces = su_dungService.delete(Long.parseLong(tblDichVuDaSD.getValueAt(i, 1).toString()));
                    if (rowSucces > 0) {
                        succesDeltete += "\t" + tblDichVuDaSD.getValueAt(i, 1).toString() + "\n";
                    } else {
                        errDeltete += "\t" + tblDichVuDaSD.getValueAt(i, 1).toString() + "\n";
                    }
                }
            }
            tblDichVuDaSD.clearSelection();
            loadDataSDDV();
            if (check == true) {
                String mess = "";
                if (succesDeltete.length() > 0) {
                    mess += "Bạn đã xóa thành công: \n" + succesDeltete;
                }
                if (errDeltete.length() > 0) {
                    mess += "Không thể xóa: \n" + errDeltete;
                }
                JOptionPane.showMessageDialog(rootPane, mess, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hàng để xóa", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<dich_vuModel> comboDichVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaPhong;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblDichVuDaSD;
    private javax.swing.JLabel txtErrorMaSDDichVu;
    private javax.swing.JLabel txtErrorSoLuong;
    private javax.swing.JSpinner txtSoLuong;
    private javax.swing.JLabel txt_IDSDDV;
    // End of variables declaration//GEN-END:variables
}
