/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views.JintenalFrame;

import com.QLKS.Service.impl.dich_vuService;
import com.QLKS.Service.impl.don_viService;
import com.QLKS.Service.impl.loai_dich_vuService;
import com.QLKS.model.dich_vuModel;
import com.QLKS.model.don_viModel;
import com.QLKS.model.loai_dich_vuModel;
import com.QLKS.utils.functionBase;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author steve
 */
public class ITN_quan_ly_dichvu extends javax.swing.JInternalFrame {

    /**
     * Creates new form ITN_quan_ly_loaidichvu
     */
    List<loai_dich_vuModel> list_loai_dich_vu;
    List<dich_vuModel> list_dich_vu;
    dich_vuModel dichModel;
    dich_vuService dich_vuService;
    loai_dich_vuService loai_dich_vuService;
    DefaultTableModel dfmDichVu;
    DefaultComboBoxModel<loai_dich_vuModel> modelLoai_dich_vu;
    DefaultComboBoxModel<don_viModel> modelDon_vi;
    don_viService don_viService;
    List<don_viModel> list_don_vi;
    functionBase funBase;
    
    public ITN_quan_ly_dichvu() {
        initComponents();
        dichModel = new dich_vuModel();
        dich_vuService = new dich_vuService();
        loai_dich_vuService = new loai_dich_vuService();
        don_viService = new don_viService();
        dfmDichVu = new DefaultTableModel();
        modelLoai_dich_vu = new DefaultComboBoxModel();
        modelDon_vi = new DefaultComboBoxModel();
        list_loai_dich_vu = loai_dich_vuService.findAll();
        list_don_vi = don_viService.findAll();
        funBase = new functionBase();
        initLoaiDichVu();
        initDonVi();
        loadData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu_icon = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jpnDichVu = new javax.swing.JPanel();
        jlbMaDv = new javax.swing.JLabel();
        jlbMaloaiDV = new javax.swing.JLabel();
        jlbGiaDV = new javax.swing.JLabel();
        txtErrorMaLoaiDichVu = new javax.swing.JLabel();
        comboLDV = new javax.swing.JComboBox<>();
        txtErrorTenLoaiDichVu = new javax.swing.JLabel();
        txtGiaDichVu = new javax.swing.JTextField();
        txtErrorTenLoaiDichVu1 = new javax.swing.JLabel();
        button_resset = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        button_addDV = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        button_update = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        button_delete = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_idDV = new javax.swing.JLabel();
        txtErrorTenLoaiDichVu2 = new javax.swing.JLabel();
        comboDon_vi = new javax.swing.JComboBox<>();
        jlbMaloaiDV1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldichVu = new javax.swing.JTable();
        txtSearchMaLoaiDV = new javax.swing.JTextField();
        txtSearchTenLoaiDV = new javax.swing.JTextField();
        jlbMaDv1 = new javax.swing.JLabel();
        jlbTenDv1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        header.setBackground(new java.awt.Color(8, 13, 23));
        header.setMaximumSize(new java.awt.Dimension(876, 50));
        header.setMinimumSize(new java.awt.Dimension(876, 50));
        header.setPreferredSize(new java.awt.Dimension(876, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 231, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý dịch vụ");

        menu_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/custom-iconMenu.png"))); // NOI18N
        menu_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_iconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(menu_icon)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_icon)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        content.setBackground(new java.awt.Color(48, 48, 48));

        jpnDichVu.setBackground(new java.awt.Color(48, 48, 48));
        jpnDichVu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(154, 231, 246))); // NOI18N

        jlbMaDv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbMaDv.setForeground(new java.awt.Color(154, 231, 246));
        jlbMaDv.setText("Mã dịch vụ:");

        jlbMaloaiDV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbMaloaiDV.setForeground(new java.awt.Color(154, 231, 246));
        jlbMaloaiDV.setText("Mã loại dịch vụ:");

        jlbGiaDV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbGiaDV.setForeground(new java.awt.Color(154, 231, 246));
        jlbGiaDV.setText("Giá dịch vụ:");

        txtErrorMaLoaiDichVu.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorMaLoaiDichVu.setText("...");

        txtErrorTenLoaiDichVu.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorTenLoaiDichVu.setText("...");

        txtGiaDichVu.setBackground(new java.awt.Color(32, 32, 32));
        txtGiaDichVu.setColumns(5);
        txtGiaDichVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtGiaDichVu.setForeground(new java.awt.Color(154, 231, 246));
        txtGiaDichVu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txtGiaDichVu.setCaretColor(new java.awt.Color(154, 231, 246));

        txtErrorTenLoaiDichVu1.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorTenLoaiDichVu1.setText("...");

        button_resset.setBackground(new java.awt.Color(36, 36, 36));
        button_resset.setMaximumSize(new java.awt.Dimension(100, 35));
        button_resset.setMinimumSize(new java.awt.Dimension(100, 35));
        button_resset.setPreferredSize(new java.awt.Dimension(90, 30));
        button_resset.setLayout(new java.awt.BorderLayout());

        jLabel3.setForeground(new java.awt.Color(154, 231, 246));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Làm mới");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        button_resset.add(jLabel3, java.awt.BorderLayout.CENTER);

        button_addDV.setBackground(new java.awt.Color(36, 36, 36));
        button_addDV.setMaximumSize(new java.awt.Dimension(100, 35));
        button_addDV.setMinimumSize(new java.awt.Dimension(100, 35));
        button_addDV.setPreferredSize(new java.awt.Dimension(90, 30));
        button_addDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_addDVMouseClicked(evt);
            }
        });
        button_addDV.setLayout(new java.awt.BorderLayout());

        jLabel4.setForeground(new java.awt.Color(154, 231, 246));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm mới");
        button_addDV.add(jLabel4, java.awt.BorderLayout.CENTER);

        button_update.setBackground(new java.awt.Color(36, 36, 36));
        button_update.setMaximumSize(new java.awt.Dimension(100, 35));
        button_update.setMinimumSize(new java.awt.Dimension(100, 35));
        button_update.setPreferredSize(new java.awt.Dimension(90, 30));
        button_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_updateMouseClicked(evt);
            }
        });
        button_update.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(154, 231, 246));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cập nhật");
        button_update.add(jLabel5, java.awt.BorderLayout.CENTER);

        button_delete.setBackground(new java.awt.Color(36, 36, 36));
        button_delete.setMaximumSize(new java.awt.Dimension(100, 35));
        button_delete.setMinimumSize(new java.awt.Dimension(100, 35));
        button_delete.setPreferredSize(new java.awt.Dimension(90, 30));
        button_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_deleteMouseEntered(evt);
            }
        });
        button_delete.setLayout(new java.awt.BorderLayout());

        jLabel6.setForeground(new java.awt.Color(154, 231, 246));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Xoá");
        button_delete.add(jLabel6, java.awt.BorderLayout.CENTER);

        txt_idDV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_idDV.setForeground(new java.awt.Color(154, 231, 246));

        txtErrorTenLoaiDichVu2.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorTenLoaiDichVu2.setText("...");

        jlbMaloaiDV1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbMaloaiDV1.setForeground(new java.awt.Color(154, 231, 246));
        jlbMaloaiDV1.setText("Loại Đơn Vị");

        javax.swing.GroupLayout jpnDichVuLayout = new javax.swing.GroupLayout(jpnDichVu);
        jpnDichVu.setLayout(jpnDichVuLayout);
        jpnDichVuLayout.setHorizontalGroup(
            jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDichVuLayout.createSequentialGroup()
                        .addComponent(jlbGiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGiaDichVu)
                            .addGroup(jpnDichVuLayout.createSequentialGroup()
                                .addComponent(txtErrorTenLoaiDichVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpnDichVuLayout.createSequentialGroup()
                        .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbMaDv)
                            .addComponent(jlbMaloaiDV))
                        .addGap(18, 18, 18)
                        .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtErrorMaLoaiDichVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErrorTenLoaiDichVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpnDichVuLayout.createSequentialGroup()
                                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboLDV, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_idDV, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpnDichVuLayout.createSequentialGroup()
                        .addComponent(button_resset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_addDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnDichVuLayout.createSequentialGroup()
                        .addComponent(jlbMaloaiDV1)
                        .addGap(40, 40, 40)
                        .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtErrorTenLoaiDichVu2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDon_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnDichVuLayout.setVerticalGroup(
            jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDichVuLayout.createSequentialGroup()
                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnDichVuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbMaDv))
                    .addGroup(jpnDichVuLayout.createSequentialGroup()
                        .addComponent(txt_idDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addComponent(txtErrorMaLoaiDichVu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaloaiDV)
                    .addComponent(comboLDV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorTenLoaiDichVu)
                .addGap(18, 18, 18)
                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaloaiDV1)
                    .addComponent(comboDon_vi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorTenLoaiDichVu2)
                .addGap(28, 28, 28)
                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbGiaDV)
                    .addComponent(txtGiaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorTenLoaiDichVu1)
                .addGap(34, 34, 34)
                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_resset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_addDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(48, 48, 48));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbldichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbldichVu);

        txtSearchMaLoaiDV.setBackground(new java.awt.Color(32, 32, 32));
        txtSearchMaLoaiDV.setForeground(new java.awt.Color(154, 231, 246));

        txtSearchTenLoaiDV.setBackground(new java.awt.Color(32, 32, 32));
        txtSearchTenLoaiDV.setForeground(new java.awt.Color(154, 231, 246));
        txtSearchTenLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchTenLoaiDVActionPerformed(evt);
            }
        });

        jlbMaDv1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jlbMaDv1.setForeground(new java.awt.Color(154, 231, 246));
        jlbMaDv1.setText("Mã dịch vụ:");

        jlbTenDv1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jlbTenDv1.setForeground(new java.awt.Color(154, 231, 246));
        jlbTenDv1.setText("Tên dịch vụ:");

        jPanel4.setBackground(new java.awt.Color(32, 32, 32));
        jPanel4.setPreferredSize(new java.awt.Dimension(149, 21));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(32, 32, 32));
        jLabel2.setForeground(new java.awt.Color(154, 231, 246));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tìm kiếm");
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchMaLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMaDv1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTenDv1)
                    .addComponent(txtSearchTenLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbMaDv1)
                            .addComponent(jlbTenDv1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchMaLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtSearchTenLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ressetText() {
        txt_idDV.setText("");
        txtGiaDichVu.setText("");
    }
    
    public void initLoaiDichVu() {
        for (loai_dich_vuModel modelLDV : list_loai_dich_vu) {
            modelLoai_dich_vu.addElement(modelLDV
            );
        }
        comboLDV.setModel(modelLoai_dich_vu);
    }
    
    public void initDonVi() {
        for (don_viModel modelDV : list_don_vi) {
            modelDon_vi.addElement(modelDV);
        }
        comboDon_vi.setModel(modelDon_vi);
        
    }
    
    public void loadData() {
        Object[] columnNames = {"STT", "Mã Dịch Vụ", "Tên loại Dịch Vụ", "Giá", "Đơn Vị", ""};
//        if (nameSeaechInput != null) {
//            dfmThietBi = thiet_biService.search(nameSeaechInput);
//        } else {
//            dfmThietBi = cauhinhDAO.getAll();
//        }
        list_dich_vu = dich_vuService.findAll();
        
        dfmDichVu = new DefaultTableModel(new Object[0][0], columnNames);
        int index = 1;
        for (dich_vuModel adv : list_dich_vu) {
            Object[] o = new Object[6];
            o[0] = index;
            o[1] = adv.getId();
            o[2] = adv.getLoai_dich_vuModel().getName();
            o[3] = adv.getPrice();
            o[4] = adv.getDon_viModel().getName_DV();
            dfmDichVu.addRow(o);
            index++;
        }
        tbldichVu.setModel(dfmDichVu);
        funBase.addCheckBox(5, tbldichVu);

        // Cài đặt sự kiện khi click từng dòng trong bảng
        if (list_dich_vu.size() > 0) {
            
            tbldichVu.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    int currentRow = tbldichVu.getSelectedRow();
                    if (currentRow < 0) {
                        currentRow = 0;
                    }

                    // Chèn dữ liệu lên form
                    if (currentRow >= 0) {
                        txt_idDV.setText(tbldichVu.getValueAt(currentRow, 1).toString());
                        txtGiaDichVu.setText(tbldichVu.getValueAt(currentRow, 3).toString());
                    }
                }
            });
        }
    }
    private void menu_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseClicked

    }//GEN-LAST:event_menu_iconMouseClicked

    private void menu_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseEntered

    }//GEN-LAST:event_menu_iconMouseEntered

    private void menu_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseExited

    }//GEN-LAST:event_menu_iconMouseExited

    private void txtSearchTenLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchTenLoaiDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTenLoaiDVActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        ressetText();
        loadData();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void button_addDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_addDVMouseClicked
        Float giadich_vu = Float.parseFloat(txtGiaDichVu.getText());
        loai_dich_vuModel loaiDV = (loai_dich_vuModel) modelLoai_dich_vu.getSelectedItem();
        Long id_LDVM = loaiDV.getId();
        don_viModel don_viCB = (don_viModel) modelDon_vi.getSelectedItem();
        Long id_DonVi = don_viCB.getId();
        boolean check_DV = true;
        if (giadich_vu == 0) {
            txtErrorTenLoaiDichVu1.setText("Giá Không được để trốnng!");
            check_DV = false;
        } else {
            txtErrorTenLoaiDichVu1.setText("");
        }
        
        if (check_DV == true) {
            dichModel.setId_LDV(id_LDVM);
            dichModel.setId_DV(id_DonVi);
            dichModel.setPrice(giadich_vu);
            Long key = dich_vuService.add(dichModel);
            if (key > 0) {
                JOptionPane.showMessageDialog(this, "Thêm Mới Thành Công!");
                ressetText();
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm Mới Thất Bại!");
            }
        }
    }//GEN-LAST:event_button_addDVMouseClicked

    private void button_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_updateMouseClicked
        Long id_dich_vu = Long.parseLong(txt_idDV.getText());
        Float giadich_vu = Float.parseFloat(txtGiaDichVu.getText());
        loai_dich_vuModel loaiDV = (loai_dich_vuModel) modelLoai_dich_vu.getSelectedItem();
        Long id_LDVM = loaiDV.getId();
        don_viModel don_viCB = (don_viModel) modelDon_vi.getSelectedItem();
        Long id_DonVi = don_viCB.getId();
        boolean check_DV = true;
        if (giadich_vu == 0) {
            txtErrorTenLoaiDichVu1.setText("Giá Không được để trốnng!");
            check_DV = false;
        } else {
            txtErrorTenLoaiDichVu1.setText("");
        }
        
        if (check_DV == true) {
            dichModel.setId(id_dich_vu);
            dichModel.setId_LDV(id_LDVM);
            dichModel.setId_DV(id_DonVi);
            dichModel.setPrice(giadich_vu);
            int key = dich_vuService.edit(dichModel);
            if (key > 0) {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công!");
                ressetText();
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thất Bại!");
                loadData();
            }
        }
    }//GEN-LAST:event_button_updateMouseClicked

    private void button_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_deleteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button_deleteMouseEntered

    private void button_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_deleteMouseClicked
         String succesDeltete = "";
        String errDeltete = "";
        boolean check_del = false;

        int thongBao = JOptionPane.showConfirmDialog(this, "Bạn có chắc không?", "Thông báo!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (thongBao == JOptionPane.YES_OPTION) {

            for (int i = 0; i < tbldichVu.getRowCount(); i++) {
                if (funBase.IsSelected(i, 5, tbldichVu)) {
                    check_del = true;
                    int rowSuccess = dich_vuService.delete(Long.parseLong(tbldichVu.getValueAt(i, 1).toString()));
                    tbldichVu.clearSelection();
                    if (rowSuccess > 0) {
                        succesDeltete += "\t" + tbldichVu.getValueAt(i, 2).toString() + "\n";
                    } else {
                        errDeltete += "\t" + tbldichVu.getValueAt(i, 2).toString() + "\n";
                    }
                }
            }
            loadData();
            ressetText();
            if (check_del == true) {
                String mess = "";
                if (succesDeltete.length() > 0) {
                    mess += "Bạn đã xóa thành công: \n" + succesDeltete;
                }
                if (errDeltete.length() > 0) {
                    mess += "Không thể xóa: \n" + errDeltete;
                }
                JOptionPane.showMessageDialog(rootPane, mess, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hàng để xóa", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_button_deleteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button_addDV;
    private javax.swing.JPanel button_delete;
    private javax.swing.JPanel button_resset;
    private javax.swing.JPanel button_update;
    private javax.swing.JComboBox<don_viModel> comboDon_vi;
    private javax.swing.JComboBox<loai_dich_vuModel> comboLDV;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbGiaDV;
    private javax.swing.JLabel jlbMaDv;
    private javax.swing.JLabel jlbMaDv1;
    private javax.swing.JLabel jlbMaloaiDV;
    private javax.swing.JLabel jlbMaloaiDV1;
    private javax.swing.JLabel jlbTenDv1;
    private javax.swing.JPanel jpnDichVu;
    private javax.swing.JLabel menu_icon;
    private javax.swing.JTable tbldichVu;
    private javax.swing.JLabel txtErrorMaLoaiDichVu;
    private javax.swing.JLabel txtErrorTenLoaiDichVu;
    private javax.swing.JLabel txtErrorTenLoaiDichVu1;
    private javax.swing.JLabel txtErrorTenLoaiDichVu2;
    private javax.swing.JTextField txtGiaDichVu;
    private javax.swing.JTextField txtSearchMaLoaiDV;
    private javax.swing.JTextField txtSearchTenLoaiDV;
    private javax.swing.JLabel txt_idDV;
    // End of variables declaration//GEN-END:variables
}
