/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views.JintenalFrame;

import com.QLKS.Service.impl.don_viService;
import com.QLKS.model.don_viModel;
import com.QLKS.model.loai_dich_vuModel;
import com.QLKS.utils.functionBase;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author steve
 */
public class ITN_quan_ly_donvi extends javax.swing.JInternalFrame {

    /**
     * Creates new form ITN_quan_ly_loaidichvu
     */
    List<don_viModel> list_don_vi;
    don_viModel don_viModel;
    DefaultTableModel dfmDonVi;
    don_viService don_viService;
    functionBase funBase;

    public ITN_quan_ly_donvi() {
        initComponents();
        don_viModel = new don_viModel();
        dfmDonVi = new DefaultTableModel();
        don_viService = new don_viService();
        funBase = new functionBase();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu_icon = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jpnDichVu = new javax.swing.JPanel();
        jlbMaDvi = new javax.swing.JLabel();
        jlbTenDVi = new javax.swing.JLabel();
        txtErrorMadonvi = new javax.swing.JLabel();
        txtErrorTendonvi = new javax.swing.JLabel();
        txtTendonvi = new javax.swing.JTextField();
        buttonResset = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        button_updateDv = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        delete_don_vi = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_idDV = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonVi = new javax.swing.JTable();
        txtSearchTenLoaiDV = new javax.swing.JTextField();
        jlbTenDv1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        header.setBackground(new java.awt.Color(8, 13, 23));
        header.setMaximumSize(new java.awt.Dimension(876, 50));
        header.setMinimumSize(new java.awt.Dimension(876, 50));
        header.setPreferredSize(new java.awt.Dimension(876, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 231, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý đơn vị");

        menu_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/custom-iconMenu.png"))); // NOI18N
        menu_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_iconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(menu_icon)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_icon)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        content.setBackground(new java.awt.Color(48, 48, 48));

        jpnDichVu.setBackground(new java.awt.Color(48, 48, 48));
        jpnDichVu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đơn vị", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(154, 231, 246))); // NOI18N

        jlbMaDvi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbMaDvi.setForeground(new java.awt.Color(154, 231, 246));
        jlbMaDvi.setText("Mã đơn vị:");

        jlbTenDVi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbTenDVi.setForeground(new java.awt.Color(154, 231, 246));
        jlbTenDVi.setText("Tên đơn vị:");

        txtErrorMadonvi.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorMadonvi.setText("...");

        txtErrorTendonvi.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorTendonvi.setText("...");

        txtTendonvi.setBackground(new java.awt.Color(32, 32, 32));
        txtTendonvi.setColumns(5);
        txtTendonvi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTendonvi.setForeground(new java.awt.Color(154, 231, 246));
        txtTendonvi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txtTendonvi.setCaretColor(new java.awt.Color(154, 231, 246));

        buttonResset.setBackground(new java.awt.Color(36, 36, 36));
        buttonResset.setMaximumSize(new java.awt.Dimension(100, 35));
        buttonResset.setMinimumSize(new java.awt.Dimension(100, 35));
        buttonResset.setPreferredSize(new java.awt.Dimension(90, 30));
        buttonResset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRessetMouseClicked(evt);
            }
        });
        buttonResset.setLayout(new java.awt.BorderLayout());

        jLabel3.setForeground(new java.awt.Color(154, 231, 246));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Làm mới");
        buttonResset.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(36, 36, 36));
        jPanel7.setMaximumSize(new java.awt.Dimension(100, 35));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 35));
        jPanel7.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setForeground(new java.awt.Color(154, 231, 246));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm mới");
        jPanel7.add(jLabel4, java.awt.BorderLayout.CENTER);

        button_updateDv.setBackground(new java.awt.Color(36, 36, 36));
        button_updateDv.setMaximumSize(new java.awt.Dimension(100, 35));
        button_updateDv.setMinimumSize(new java.awt.Dimension(100, 35));
        button_updateDv.setPreferredSize(new java.awt.Dimension(90, 30));
        button_updateDv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_updateDvMouseClicked(evt);
            }
        });
        button_updateDv.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(154, 231, 246));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cập nhật");
        button_updateDv.add(jLabel5, java.awt.BorderLayout.CENTER);

        delete_don_vi.setBackground(new java.awt.Color(36, 36, 36));
        delete_don_vi.setMaximumSize(new java.awt.Dimension(100, 35));
        delete_don_vi.setMinimumSize(new java.awt.Dimension(100, 35));
        delete_don_vi.setPreferredSize(new java.awt.Dimension(90, 30));
        delete_don_vi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_don_viMouseClicked(evt);
            }
        });
        delete_don_vi.setLayout(new java.awt.BorderLayout());

        jLabel6.setForeground(new java.awt.Color(154, 231, 246));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Xoá");
        delete_don_vi.add(jLabel6, java.awt.BorderLayout.CENTER);

        txt_idDV.setBackground(new java.awt.Color(48, 48, 48));
        txt_idDV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_idDV.setForeground(new java.awt.Color(154, 231, 246));

        javax.swing.GroupLayout jpnDichVuLayout = new javax.swing.GroupLayout(jpnDichVu);
        jpnDichVu.setLayout(jpnDichVuLayout);
        jpnDichVuLayout.setHorizontalGroup(
            jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDichVuLayout.createSequentialGroup()
                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDichVuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbTenDVi, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jlbMaDvi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTendonvi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtErrorMadonvi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErrorTendonvi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpnDichVuLayout.createSequentialGroup()
                                .addComponent(txt_idDV, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpnDichVuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonResset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_updateDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_don_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnDichVuLayout.setVerticalGroup(
            jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDichVuLayout.createSequentialGroup()
                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnDichVuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbMaDvi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_idDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorMadonvi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTendonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTenDVi))
                .addGap(1, 1, 1)
                .addComponent(txtErrorTendonvi)
                .addGap(75, 75, 75)
                .addGroup(jpnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonResset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_updateDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_don_vi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(48, 48, 48));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDonVi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDonVi);

        txtSearchTenLoaiDV.setBackground(new java.awt.Color(32, 32, 32));
        txtSearchTenLoaiDV.setForeground(new java.awt.Color(154, 231, 246));
        txtSearchTenLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchTenLoaiDVActionPerformed(evt);
            }
        });

        jlbTenDv1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jlbTenDv1.setForeground(new java.awt.Color(154, 231, 246));
        jlbTenDv1.setText("Tên đơn vị:");

        jPanel4.setBackground(new java.awt.Color(32, 32, 32));
        jPanel4.setPreferredSize(new java.awt.Dimension(149, 21));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(32, 32, 32));
        jLabel2.setForeground(new java.awt.Color(154, 231, 246));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tìm kiếm");
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jlbTenDv1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchTenLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchTenLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbTenDv1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ressetText() {
        txt_idDV.setText("");
        txtTendonvi.setText("");
        txtErrorTendonvi.setText("");
    }

    public void loadData() {
        Object[] columnNames = {"STT", "Mã Đơn Vị", "Tên Đơn Vị", ""};
//        if (nameSeaechInput != null) {
//            dfmThietBi = thiet_biService.search(nameSeaechInput);
//        } else {
//            dfmThietBi = cauhinhDAO.getAll();
//        }
        list_don_vi = don_viService.findAll();

        dfmDonVi = new DefaultTableModel(new Object[0][0], columnNames);
        int index = 1;
        for (don_viModel adv : list_don_vi) {
            Object[] o = new Object[4];
            o[0] = index;
            o[1] = adv.getId();
            o[2] = adv.getName_DV();
            dfmDonVi.addRow(o);
            index++;
        }
        tblDonVi.setModel(dfmDonVi);
        funBase.addCheckBox(3, tblDonVi);

        // Cài đặt sự kiện khi click từng dòng trong bảng
        if (list_don_vi.size() > 0) {
            tblDonVi.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    int currentRow = tblDonVi.getSelectedRow();
                    if (currentRow < 0) {
                        currentRow = 0;
                    }
                    // Chèn dữ liệu lên form
                    if (currentRow >= 0) {
                        txt_idDV.setText(tblDonVi.getValueAt(currentRow, 1).toString());
                        txtTendonvi.setText(tblDonVi.getValueAt(currentRow, 2).toString());
                    }
                }
            });
        }
    }
    private void menu_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseClicked

    }//GEN-LAST:event_menu_iconMouseClicked

    private void menu_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseEntered

    }//GEN-LAST:event_menu_iconMouseEntered

    private void menu_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseExited

    }//GEN-LAST:event_menu_iconMouseExited

    private void txtSearchTenLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchTenLoaiDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTenLoaiDVActionPerformed

    private void buttonRessetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRessetMouseClicked
        ressetText();
        loadData();
    }//GEN-LAST:event_buttonRessetMouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        String name_don_vi = txtTendonvi.getText();
        boolean check_Don_Vi = true;
        if (name_don_vi.length() == 0) {
            txtErrorTendonvi.setText("Tên Đơn Vị Không Được Để Trống!");
            check_Don_Vi = false;
        } else {
            txtTendonvi.setText("");
        }

        if (check_Don_Vi == true) {
            don_viModel getNameModel = don_viService.findByName(name_don_vi);
            if (getNameModel == null) {
                don_viModel.setName_DV(name_don_vi);
                Long key = don_viService.add(don_viModel);
                if (key > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thành Công!");
                    ressetText();
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thất Bại!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Đơn Vị đã tồn tại!");
            }
        }
    }//GEN-LAST:event_jPanel7MouseClicked

    private void button_updateDvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_updateDvMouseClicked
        Long id_don_vi = Long.parseLong(txt_idDV.getText());
        String name_don_vi = txtTendonvi.getText();
        boolean check_Don_Vi = true;
        if (name_don_vi.length() == 0) {
            txtErrorTendonvi.setText("Tên Đơn Vị Không Được Để Trống!");
            check_Don_Vi = false;
        } else {
            txtTendonvi.setText("");
        }

        if (check_Don_Vi == true) {
            don_viModel.setId(id_don_vi);
            don_viModel.setName_DV(name_don_vi);
            int key = don_viService.edit(don_viModel);
            if (key > 0) {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công!");
                ressetText();
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Cập Nhật Thất Bại!");
            }
        }
    }//GEN-LAST:event_button_updateDvMouseClicked

    private void delete_don_viMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_don_viMouseClicked
       String succesDeltete = "";
        String errDeltete = "";
        boolean check_del = false;

        int thongBao = JOptionPane.showConfirmDialog(this, "Bạn có chắc không?", "Thông báo!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (thongBao == JOptionPane.YES_OPTION) {

            for (int i = 0; i < tblDonVi.getRowCount(); i++) {
                if (funBase.IsSelected(i, 3, tblDonVi)) {
                    check_del = true;
                    int rowSuccess = don_viService.delete(Long.parseLong(tblDonVi.getValueAt(i, 1).toString()));
                    tblDonVi.clearSelection();
                    if (rowSuccess > 0) {
                        succesDeltete += "\t" + tblDonVi.getValueAt(i, 2).toString() + "\n";
                    } else {
                        errDeltete += "\t" + tblDonVi.getValueAt(i, 2).toString() + "\n";
                    }
                }
            }
            ressetText();
            loadData();
            if (check_del == true) {
                String mess = "";
                if (succesDeltete.length() > 0) {
                    mess += "Bạn đã xóa thành công: \n" + succesDeltete;

                }
                if (errDeltete.length() > 0) {
                    mess += "Không thể xóa: \n" + errDeltete;
                }
                JOptionPane.showMessageDialog(rootPane, mess, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hàng để xóa", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_delete_don_viMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonResset;
    private javax.swing.JPanel button_updateDv;
    private javax.swing.JPanel content;
    private javax.swing.JPanel delete_don_vi;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbMaDvi;
    private javax.swing.JLabel jlbTenDVi;
    private javax.swing.JLabel jlbTenDv1;
    private javax.swing.JPanel jpnDichVu;
    private javax.swing.JLabel menu_icon;
    private javax.swing.JTable tblDonVi;
    private javax.swing.JLabel txtErrorMadonvi;
    private javax.swing.JLabel txtErrorTendonvi;
    private javax.swing.JTextField txtSearchTenLoaiDV;
    private javax.swing.JTextField txtTendonvi;
    private javax.swing.JLabel txt_idDV;
    // End of variables declaration//GEN-END:variables
}
