/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views.JintenalFrame;

import com.QLKS.Service.impl.loai_dich_vuService;
import com.QLKS.model.loai_dich_vuModel;
import com.QLKS.model.loai_phongModel;
import com.QLKS.utils.functionBase;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author steve
 */
public class ITN_quan_ly_loaidichvu extends javax.swing.JInternalFrame {

    /**
     * Creates new form ITN_quan_ly_loaidichvu
     */
    loai_dich_vuModel loai_dich_vuModel;
    loai_dich_vuService loai_dich_vuService;
    List<loai_dich_vuModel> list_LDV;
    DefaultTableModel dfmLoaiDichVu;
    functionBase funBase;

    public ITN_quan_ly_loaidichvu() {
        initComponents();
        loai_dich_vuModel = new loai_dich_vuModel();
        loai_dich_vuService = new loai_dich_vuService();
        dfmLoaiDichVu = new DefaultTableModel();
        funBase = new functionBase();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu_icon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jpnLoaiDichVu = new javax.swing.JPanel();
        jlbMaLoaiDv1 = new javax.swing.JLabel();
        jlbTenLoaiDv1 = new javax.swing.JLabel();
        txtTenLoaiDichVu = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();
        txtMaLoaiDichVu = new javax.swing.JTextField();
        txtErrorMaLoaiDichVu = new javax.swing.JLabel();
        txtErrorTenLoaiDichVu = new javax.swing.JLabel();
        button_reset = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        button_add_LDV = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        button_updateLDV = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        button_delete = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiDichVu = new javax.swing.JTable();
        txtSearchMaLoaiDV = new javax.swing.JTextField();
        txtSearchTenLoaiDV = new javax.swing.JTextField();
        jlbMaLoaiDv = new javax.swing.JLabel();
        jlbTenLoaiDv = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(8, 13, 23));
        jPanel1.setMaximumSize(new java.awt.Dimension(876, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(876, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(876, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 231, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý loại dịch vụ");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        menu_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/custom-iconMenu.png"))); // NOI18N
        menu_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_iconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_iconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_iconMouseExited(evt);
            }
        });
        jPanel1.add(menu_icon, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(48, 48, 48));

        jpnLoaiDichVu.setBackground(new java.awt.Color(48, 48, 48));
        jpnLoaiDichVu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loại dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(154, 231, 246))); // NOI18N

        jlbMaLoaiDv1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbMaLoaiDv1.setForeground(new java.awt.Color(154, 231, 246));
        jlbMaLoaiDv1.setText("Mã loại dịch vụ:");
        jlbMaLoaiDv1.setMaximumSize(new java.awt.Dimension(90, 30));
        jlbMaLoaiDv1.setMinimumSize(new java.awt.Dimension(90, 30));
        jlbMaLoaiDv1.setPreferredSize(new java.awt.Dimension(90, 30));

        jlbTenLoaiDv1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlbTenLoaiDv1.setForeground(new java.awt.Color(154, 231, 246));
        jlbTenLoaiDv1.setText("Tên loại dịch vụ:");
        jlbTenLoaiDv1.setMaximumSize(new java.awt.Dimension(90, 30));
        jlbTenLoaiDv1.setMinimumSize(new java.awt.Dimension(90, 30));
        jlbTenLoaiDv1.setPreferredSize(new java.awt.Dimension(90, 30));

        txtTenLoaiDichVu.setBackground(new java.awt.Color(32, 32, 32));
        txtTenLoaiDichVu.setColumns(5);
        txtTenLoaiDichVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTenLoaiDichVu.setForeground(new java.awt.Color(154, 231, 246));
        txtTenLoaiDichVu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        txtTenLoaiDichVu.setCaretColor(new java.awt.Color(154, 231, 246));
        txtTenLoaiDichVu.setPreferredSize(new java.awt.Dimension(85, 30));

        lblResult.setForeground(new java.awt.Color(248, 13, 33));

        txtMaLoaiDichVu.setEditable(false);
        txtMaLoaiDichVu.setBackground(new java.awt.Color(32, 32, 32));
        txtMaLoaiDichVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaLoaiDichVu.setForeground(new java.awt.Color(154, 231, 246));
        txtMaLoaiDichVu.setPreferredSize(new java.awt.Dimension(6, 30));

        txtErrorMaLoaiDichVu.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorMaLoaiDichVu.setText("...");
        txtErrorMaLoaiDichVu.setMaximumSize(new java.awt.Dimension(12, 20));
        txtErrorMaLoaiDichVu.setMinimumSize(new java.awt.Dimension(12, 20));
        txtErrorMaLoaiDichVu.setPreferredSize(new java.awt.Dimension(12, 20));

        txtErrorTenLoaiDichVu.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorTenLoaiDichVu.setText("...");
        txtErrorTenLoaiDichVu.setMaximumSize(new java.awt.Dimension(12, 20));
        txtErrorTenLoaiDichVu.setMinimumSize(new java.awt.Dimension(12, 20));
        txtErrorTenLoaiDichVu.setPreferredSize(new java.awt.Dimension(390, 20));

        button_reset.setBackground(new java.awt.Color(36, 36, 36));
        button_reset.setMaximumSize(new java.awt.Dimension(100, 35));
        button_reset.setMinimumSize(new java.awt.Dimension(100, 35));
        button_reset.setPreferredSize(new java.awt.Dimension(90, 30));
        button_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_resetMouseClicked(evt);
            }
        });
        button_reset.setLayout(new java.awt.BorderLayout());

        jLabel3.setForeground(new java.awt.Color(154, 231, 246));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Làm mới");
        button_reset.add(jLabel3, java.awt.BorderLayout.CENTER);

        button_add_LDV.setBackground(new java.awt.Color(36, 36, 36));
        button_add_LDV.setMaximumSize(new java.awt.Dimension(100, 35));
        button_add_LDV.setMinimumSize(new java.awt.Dimension(100, 35));
        button_add_LDV.setPreferredSize(new java.awt.Dimension(90, 30));
        button_add_LDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_add_LDVMouseClicked(evt);
            }
        });
        button_add_LDV.setLayout(new java.awt.BorderLayout());

        jLabel4.setForeground(new java.awt.Color(154, 231, 246));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm mới");
        button_add_LDV.add(jLabel4, java.awt.BorderLayout.CENTER);

        button_updateLDV.setBackground(new java.awt.Color(36, 36, 36));
        button_updateLDV.setMaximumSize(new java.awt.Dimension(100, 35));
        button_updateLDV.setMinimumSize(new java.awt.Dimension(100, 35));
        button_updateLDV.setPreferredSize(new java.awt.Dimension(90, 30));
        button_updateLDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_updateLDVMouseClicked(evt);
            }
        });
        button_updateLDV.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(154, 231, 246));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cập nhật");
        button_updateLDV.add(jLabel5, java.awt.BorderLayout.CENTER);

        button_delete.setBackground(new java.awt.Color(36, 36, 36));
        button_delete.setMaximumSize(new java.awt.Dimension(100, 35));
        button_delete.setMinimumSize(new java.awt.Dimension(100, 35));
        button_delete.setPreferredSize(new java.awt.Dimension(90, 30));
        button_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_deleteMouseClicked(evt);
            }
        });
        button_delete.setLayout(new java.awt.BorderLayout());

        jLabel6.setForeground(new java.awt.Color(154, 231, 246));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Xoá");
        button_delete.add(jLabel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jpnLoaiDichVuLayout = new javax.swing.GroupLayout(jpnLoaiDichVu);
        jpnLoaiDichVu.setLayout(jpnLoaiDichVuLayout);
        jpnLoaiDichVuLayout.setHorizontalGroup(
            jpnLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoaiDichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnLoaiDichVuLayout.createSequentialGroup()
                        .addGroup(jpnLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbMaLoaiDv1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jlbTenLoaiDv1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtErrorTenLoaiDichVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErrorMaLoaiDichVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaLoaiDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoaiDichVuLayout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(146, 146, 146))
                            .addComponent(txtTenLoaiDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpnLoaiDichVuLayout.createSequentialGroup()
                        .addComponent(button_reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_add_LDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_updateLDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnLoaiDichVuLayout.setVerticalGroup(
            jpnLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoaiDichVuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpnLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaLoaiDv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaLoaiDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(txtErrorMaLoaiDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnLoaiDichVuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTenLoaiDv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenLoaiDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnLoaiDichVuLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtErrorTenLoaiDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResult)
                .addGap(58, 58, 58)
                .addGroup(jpnLoaiDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_add_LDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_updateLDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(48, 48, 48));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblLoaiDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLoaiDichVu);

        txtSearchMaLoaiDV.setBackground(new java.awt.Color(32, 32, 32));
        txtSearchMaLoaiDV.setForeground(new java.awt.Color(154, 231, 246));

        txtSearchTenLoaiDV.setBackground(new java.awt.Color(32, 32, 32));
        txtSearchTenLoaiDV.setForeground(new java.awt.Color(154, 231, 246));
        txtSearchTenLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchTenLoaiDVActionPerformed(evt);
            }
        });

        jlbMaLoaiDv.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jlbMaLoaiDv.setForeground(new java.awt.Color(154, 231, 246));
        jlbMaLoaiDv.setText("Mã Loại dịch vụ:");

        jlbTenLoaiDv.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jlbTenLoaiDv.setForeground(new java.awt.Color(154, 231, 246));
        jlbTenLoaiDv.setText("Tên loại dịch vụ:");

        jPanel4.setBackground(new java.awt.Color(32, 32, 32));
        jPanel4.setPreferredSize(new java.awt.Dimension(149, 21));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(32, 32, 32));
        jLabel2.setForeground(new java.awt.Color(154, 231, 246));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tìm kiếm");
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchMaLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMaLoaiDv))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTenLoaiDv)
                    .addComponent(txtSearchTenLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbMaLoaiDv)
                            .addComponent(jlbTenLoaiDv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchMaLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtSearchTenLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnLoaiDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnLoaiDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ressetText() {
        txtMaLoaiDichVu.setText("");
        txtTenLoaiDichVu.setText("");
        txtErrorTenLoaiDichVu.setText("");
    }

    public void loadData() {
        Object[] columnNames = {"STT", "Mã Loại Dịch Vụ", "Tên loại dịch vụ", ""};
//        if (nameSeaechInput != null) {
//            dfmThietBi = thiet_biService.search(nameSeaechInput);
//        } else {
//            dfmThietBi = cauhinhDAO.getAll();
//        }
        list_LDV = loai_dich_vuService.findAll();

        dfmLoaiDichVu = new DefaultTableModel(new Object[0][0], columnNames);
        int index = 1;
        for (loai_dich_vuModel adv : list_LDV) {
            Object[] o = new Object[4];
            o[0] = index;
            o[1] = adv.getId();
            o[2] = adv.getName();
            dfmLoaiDichVu.addRow(o);
            index++;
        }
        tblLoaiDichVu.setModel(dfmLoaiDichVu);
        funBase.addCheckBox(3, tblLoaiDichVu);

        // Cài đặt sự kiện khi click từng dòng trong bảng
        if (list_LDV.size() > 0) {
            tblLoaiDichVu.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    int currentRow = tblLoaiDichVu.getSelectedRow();
                    if (currentRow < 0) {
                        currentRow = 0;
                    }
                    // Chèn dữ liệu lên form
                    if (currentRow >= 0) {
                        txtMaLoaiDichVu.setText(tblLoaiDichVu.getValueAt(currentRow, 1).toString());
                        txtTenLoaiDichVu.setText(tblLoaiDichVu.getValueAt(currentRow, 2).toString());
                    }
                }
            });
        }
    }

    private void menu_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseClicked

    }//GEN-LAST:event_menu_iconMouseClicked

    private void menu_iconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseEntered

    }//GEN-LAST:event_menu_iconMouseEntered

    private void menu_iconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_iconMouseExited

    }//GEN-LAST:event_menu_iconMouseExited

    private void txtSearchTenLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchTenLoaiDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTenLoaiDVActionPerformed

    private void button_add_LDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_add_LDVMouseClicked
        String name_LDV = txtTenLoaiDichVu.getText();
        boolean check_err = true;
        if (name_LDV.length() == 0) {
            txtErrorTenLoaiDichVu.setText("Loại dịch vụ không được để trống!");
            check_err = false;
        } else {
            txtErrorTenLoaiDichVu.setText("");
        }

        if (check_err == true) {
            loai_dich_vuModel getNameModel = loai_dich_vuService.findByName(name_LDV);
            if (getNameModel == null) {
                loai_dich_vuModel.setName(name_LDV);
                Long keys = loai_dich_vuService.add(loai_dich_vuModel);
                if (keys >= 0) {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thành Công!");
                    ressetText();
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm Mới Thất Bại!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Loại dịch vụ đã tồn tại");
            }
        }
    }//GEN-LAST:event_button_add_LDVMouseClicked

    private void button_updateLDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_updateLDVMouseClicked
        String name_LDV = txtTenLoaiDichVu.getText();
        Long id_LDV = Long.parseLong(txtMaLoaiDichVu.getText());
        boolean check_err = true;
        if (name_LDV.length() == 0) {
            txtErrorTenLoaiDichVu.setText("Loại dịch vụ không được để trống!");
            check_err = false;
        } else {
            txtErrorTenLoaiDichVu.setText("");
        }

        if (check_err == true) {
            loai_dich_vuModel.setId(id_LDV);
            loai_dich_vuModel.setName(name_LDV);
            int key = loai_dich_vuService.edit(loai_dich_vuModel);
            if (key >= 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật Thành Công!");
                ressetText();
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật Thất Bại!");
            }
        }
    }//GEN-LAST:event_button_updateLDVMouseClicked

    private void button_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_deleteMouseClicked
        String succesDeltete = "";
        String errDeltete = "";
        boolean check_del = false;

        int thongBao = JOptionPane.showConfirmDialog(this, "Bạn có chắc không?", "Thông báo!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (thongBao == JOptionPane.YES_OPTION) {

            for (int i = 0; i < tblLoaiDichVu.getRowCount(); i++) {
                if (funBase.IsSelected(i, 3, tblLoaiDichVu)) {
                    check_del = true;
                    int rowSuccess = loai_dich_vuService.delete(Long.parseLong(tblLoaiDichVu.getValueAt(i, 1).toString()));
                    tblLoaiDichVu.clearSelection();
                    if (rowSuccess > 0) {
                        succesDeltete += "\t" + tblLoaiDichVu.getValueAt(i, 2).toString() + "\n";
                    } else {
                        errDeltete += "\t" + tblLoaiDichVu.getValueAt(i, 2).toString() + "\n";
                    }
                }
            }
            ressetText();
            loadData();
            if (check_del == true) {
                String mess = "";
                if (succesDeltete.length() > 0) {
                    mess += "Bạn đã xóa thành công: \n" + succesDeltete;

                }
                if (errDeltete.length() > 0) {
                    mess += "Không thể xóa: \n" + errDeltete;
                }
                JOptionPane.showMessageDialog(rootPane, mess, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hàng để xóa", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_button_deleteMouseClicked

    private void button_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_resetMouseClicked
        ressetText();
        loadData();
    }//GEN-LAST:event_button_resetMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button_add_LDV;
    private javax.swing.JPanel button_delete;
    private javax.swing.JPanel button_reset;
    private javax.swing.JPanel button_updateLDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbMaLoaiDv;
    private javax.swing.JLabel jlbMaLoaiDv1;
    private javax.swing.JLabel jlbTenLoaiDv;
    private javax.swing.JLabel jlbTenLoaiDv1;
    private javax.swing.JPanel jpnLoaiDichVu;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel menu_icon;
    private javax.swing.JTable tblLoaiDichVu;
    private javax.swing.JLabel txtErrorMaLoaiDichVu;
    private javax.swing.JLabel txtErrorTenLoaiDichVu;
    private javax.swing.JTextField txtMaLoaiDichVu;
    private javax.swing.JTextField txtSearchMaLoaiDV;
    private javax.swing.JTextField txtSearchTenLoaiDV;
    private javax.swing.JTextField txtTenLoaiDichVu;
    // End of variables declaration//GEN-END:variables
}
