/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QLKS.views.JintenalFrame;

import com.QLKS.SendEmail.ConfigUtility;
import com.QLKS.Service.impl.nhan_vienService;
import com.QLKS.model.nhan_vienModel;
import com.QLKS.utils.randomCode;
import com.QLKS.utils.security;
import com.QLKS.views.JintenalFrame.action.ITN_check_code_Email;
import java.awt.Dimension;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ITN_doi_mat_khau extends javax.swing.JInternalFrame implements ITN_check_code_Email.CallbackSend {

    /**
     * Creates new form ITN_doi_mat_khau
     */
    nhan_vienModel nhan_vien;
    nhan_vienService nhan_vienService;
    private JDesktopPane jdek;
    boolean check_pass = true;

    public ITN_doi_mat_khau(nhan_vienModel nhan_vien) {
        initComponents();
        this.nhan_vien = nhan_vien;
        nhan_vienService = new nhan_vienService();
    }

    public void centerJIF(JInternalFrame jif) {
        Dimension desktopSize = jdek.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }

    public void showInternalFrame(JInternalFrame jif) {
        if (!jif.isVisible()) {
            jdek = getDesktopPane();
            jdek.add(jif);
            centerJIF(jif);
            jif.setVisible(true);
            jdek.show();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        line = new javax.swing.JPanel();
        line_space = new javax.swing.JPanel();
        oldPassword = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        old_password_txt = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txt_err_password = new javax.swing.JLabel();
        newPassword = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        new_password_txt = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txt_password_new = new javax.swing.JLabel();
        nhap_laiPassword = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nhap_lai_newPassword_txt = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        txt_xn_passordnew = new javax.swing.JLabel();
        submit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(68, 68, 68));
        setBorder(null);
        setClosable(true);
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QLKS/icon/icon_button/icons8_hotel_star_20px.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(510, 474));

        jPanel1.setBackground(new java.awt.Color(27, 27, 27));
        jPanel1.setPreferredSize(new java.awt.Dimension(503, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 231, 246));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đổi Mật Khẩu");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(78, 78, 78));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        line.setBackground(new java.awt.Color(0, 0, 0));
        line.setPreferredSize(new java.awt.Dimension(503, 5));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel2.add(line);

        line_space.setBackground(new java.awt.Color(78, 78, 78));
        line_space.setPreferredSize(new java.awt.Dimension(503, 50));

        javax.swing.GroupLayout line_spaceLayout = new javax.swing.GroupLayout(line_space);
        line_space.setLayout(line_spaceLayout);
        line_spaceLayout.setHorizontalGroup(
            line_spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        line_spaceLayout.setVerticalGroup(
            line_spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(line_space);

        oldPassword.setBackground(new java.awt.Color(27, 27, 27));
        oldPassword.setPreferredSize(new java.awt.Dimension(400, 50));
        oldPassword.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(154, 231, 246));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MK hiện tại");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 50));
        oldPassword.add(jLabel2, java.awt.BorderLayout.LINE_START);

        old_password_txt.setBackground(new java.awt.Color(48, 48, 48));
        old_password_txt.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        old_password_txt.setForeground(new java.awt.Color(154, 231, 246));
        old_password_txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        old_password_txt.setCaretColor(new java.awt.Color(154, 231, 246));
        oldPassword.add(old_password_txt, java.awt.BorderLayout.CENTER);

        jPanel2.add(oldPassword);

        jPanel3.setBackground(new java.awt.Color(78, 78, 78));
        jPanel3.setPreferredSize(new java.awt.Dimension(503, 40));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(78, 78, 78));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel7.setBackground(new java.awt.Color(78, 78, 78));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setBackground(new java.awt.Color(78, 78, 78));
        jPanel8.setLayout(new java.awt.BorderLayout());

        txt_err_password.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txt_err_password.setForeground(new java.awt.Color(255, 0, 0));
        txt_err_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        jPanel8.add(txt_err_password, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        newPassword.setBackground(new java.awt.Color(27, 27, 27));
        newPassword.setPreferredSize(new java.awt.Dimension(400, 50));
        newPassword.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(154, 231, 246));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MK mới");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 50));
        newPassword.add(jLabel3, java.awt.BorderLayout.LINE_START);

        new_password_txt.setBackground(new java.awt.Color(48, 48, 48));
        new_password_txt.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        new_password_txt.setForeground(new java.awt.Color(154, 231, 246));
        new_password_txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        new_password_txt.setCaretColor(new java.awt.Color(154, 231, 246));
        newPassword.add(new_password_txt, java.awt.BorderLayout.CENTER);

        jPanel2.add(newPassword);

        jPanel4.setBackground(new java.awt.Color(78, 78, 78));
        jPanel4.setPreferredSize(new java.awt.Dimension(503, 40));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(78, 78, 78));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9, java.awt.BorderLayout.LINE_END);

        jPanel10.setBackground(new java.awt.Color(78, 78, 78));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10, java.awt.BorderLayout.LINE_START);

        jPanel11.setBackground(new java.awt.Color(78, 78, 78));
        jPanel11.setLayout(new java.awt.BorderLayout());

        txt_password_new.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txt_password_new.setForeground(new java.awt.Color(255, 0, 0));
        txt_password_new.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        jPanel11.add(txt_password_new, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        nhap_laiPassword.setBackground(new java.awt.Color(27, 27, 27));
        nhap_laiPassword.setPreferredSize(new java.awt.Dimension(400, 50));
        nhap_laiPassword.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(154, 231, 246));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nhập lại mk");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 50));
        nhap_laiPassword.add(jLabel4, java.awt.BorderLayout.LINE_START);

        nhap_lai_newPassword_txt.setBackground(new java.awt.Color(48, 48, 48));
        nhap_lai_newPassword_txt.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        nhap_lai_newPassword_txt.setForeground(new java.awt.Color(154, 231, 246));
        nhap_lai_newPassword_txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        nhap_lai_newPassword_txt.setCaretColor(new java.awt.Color(154, 231, 246));
        nhap_laiPassword.add(nhap_lai_newPassword_txt, java.awt.BorderLayout.CENTER);

        jPanel2.add(nhap_laiPassword);

        jPanel5.setBackground(new java.awt.Color(78, 78, 78));
        jPanel5.setPreferredSize(new java.awt.Dimension(503, 20));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(78, 78, 78));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel12, java.awt.BorderLayout.LINE_END);

        jPanel13.setBackground(new java.awt.Color(78, 78, 78));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel13, java.awt.BorderLayout.LINE_START);

        jPanel14.setBackground(new java.awt.Color(78, 78, 78));
        jPanel14.setLayout(new java.awt.BorderLayout());

        txt_xn_passordnew.setForeground(new java.awt.Color(204, 0, 0));
        txt_xn_passordnew.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        jPanel14.add(txt_xn_passordnew, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        submit.setBackground(new java.awt.Color(13, 13, 13));
        submit.setPreferredSize(new java.awt.Dimension(400, 50));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
        });
        submit.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(154, 231, 246));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Xác Nhận");
        submit.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(submit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean check_code_email(String oldCode, String newCode) {
        if (oldCode.equals(newCode) == true) {
            return true;
        } else {
            return false;
        }
    }
    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited

    }//GEN-LAST:event_submitMouseExited

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered

    }//GEN-LAST:event_submitMouseEntered

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        String oldPassword = new String(old_password_txt.getPassword());
        String newPassword = new String(new_password_txt.getPassword());
        String nhap_laiPassword = new String(nhap_lai_newPassword_txt.getPassword());
        
        try {
            if (oldPassword.length() == 0) {
                txt_err_password.setText("Mật khẩu không được để trống!");
                check_pass = false;
            } else if (oldPassword.length() < 8 || oldPassword.length() > 50) {
                txt_err_password.setText("Mật khẩu phải từ 8 -> 50 ký tự!");
                check_pass = false;
            } else if (security.checkPassword(oldPassword, nhan_vien.getPassword()) == false) {
                txt_err_password.setText("Mật khẩu không đúng!");
                check_pass = false;
            } else {
                txt_err_password.setText("");
            }
        } catch (Exception e) {
             e.printStackTrace();
        }

        try {
            if (newPassword.length() == 0) {
                txt_password_new.setText("Mật khẩu mới không được dể trống");
                check_pass = false;
            } else if (newPassword.length() < 8 || newPassword.length() > 50) {
                txt_password_new.setText("Mật khẩu phải từ 8 -> 50 ký tự!");
                check_pass = false;
            } else if (newPassword.equals(oldPassword) == true) {
                txt_password_new.setText("Mật khẩu mới trùng mật khẩu cũ!");
                check_pass = false;
            } else {
                txt_password_new.setText("");
            }
        } catch (Exception e) {
             e.printStackTrace();
        }

        try {
            if (nhap_laiPassword.length() == 0) {
                txt_xn_passordnew.setText("Mật khẩu nhập lại không được rỗng!");
                check_pass = false;
            } else if (nhap_laiPassword.length() < 8 || nhap_laiPassword.length() > 50) {
                txt_xn_passordnew.setText("Mật khẩu phải từ 8 -> 50 ký tự!");
                check_pass = false;
            } else if (nhap_laiPassword.equals(newPassword) == false) {
                txt_xn_passordnew.setText("Mật khẩu xác nhận không trùng!");
                check_pass = false;
            } else {
                txt_xn_passordnew.setText("");
            }
        } catch (Exception e) {
             e.printStackTrace();
        }

        if (check_pass == true) {
            nhan_vien.setPassword(newPassword);
            nhan_vien.setRandom_code_pass(String.valueOf(randomCode.randomCodeCheck(1000, 9999)));
            final String userName_email = "Nguyenbatu10111@gmail.com";
            final String password_email = "yagl aioh afxg tvvt";
            Properties pops = new Properties();
            ConfigUtility configUtility = new ConfigUtility();
            try {
                pops = configUtility.loadProperties();
            } catch (IOException ex) {
                Logger.getLogger(ITN_doi_mat_khau.class.getName()).log(Level.SEVERE, null, ex);
            }

            //dang nhap gmail
            Session session = Session.getInstance(pops, new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(userName_email, password_email);
                }
            });

            try {
                Message message = new MimeMessage(session);
                message.setFrom(new InternetAddress("Nguyenbatu10111@gmail.com"));
                message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(nhan_vien.getEmail()));
                message.setSubject("Khách Sạn XYZ");
                message.setText(nhan_vien.getRandom_code_pass());
                Transport.send(message);
                System.out.println(nhan_vien.getEmail());
                ITN_check_code_Email itn_check_email = new ITN_check_code_Email(this);
                showInternalFrame(itn_check_email);
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_submitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel line;
    private javax.swing.JPanel line_space;
    private javax.swing.JPanel newPassword;
    private javax.swing.JPasswordField new_password_txt;
    private javax.swing.JPanel nhap_laiPassword;
    private javax.swing.JPasswordField nhap_lai_newPassword_txt;
    private javax.swing.JPanel oldPassword;
    private javax.swing.JPasswordField old_password_txt;
    private javax.swing.JPanel submit;
    private javax.swing.JLabel txt_err_password;
    private javax.swing.JLabel txt_password_new;
    private javax.swing.JLabel txt_xn_passordnew;
    // End of variables declaration//GEN-END:variables

    @Override
    public void doSend(String code_send) {
        final boolean cehck_code_sendMail;
        cehck_code_sendMail = check_code_email(nhan_vien.getRandom_code_pass(), code_send);
        if (cehck_code_sendMail == true) {
            nhan_vienService.edit(nhan_vien);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thất Bại!");
        }
    }
}
